const assert=require('node:assert/strict');require('./ledger.js');const B=require('./backup.js');
(async()=>{
 const {FinanceAccount,financeAccess}=await import('./backend/finance-account.mjs'),{localNamespace}=await import('./backend/local-storage.mjs'),{ownerEnvironment,ownerBackupAccess}=await import('./backend/owner-account.mjs');const owner={data:{projects:[{id:'old',name:'Existing owner',notes:'Retain legacy source',schedule:[{id:'existing-shared',title:'Existing share',sharedWith:['*']}],todos:[],toBuy:[]}],timeEntries:[],settings:{}},updatedAt:'2026-10-02T00:00:00Z'},other={data:{projects:[{id:'other',name:'Other original',notes:'Other source untouched'}],timeEntries:[]},updatedAt:'2026-10-02T00:00:00Z'},records=new Map([['data:owner',JSON.stringify(owner)],['data:other',JSON.stringify(other)]]),ns=localNamespace(FinanceAccount,{env:{OWNER_ACTIVATE_ON_RESTORE:'true'}}),env={OWNER_ACCOUNT_MODE:'fresh-v8',OWNER_ACTIVATE_ON_RESTORE:'true',ENABLE_FINANCE_REVIEW:'true',FINANCE_ACCOUNTS:ns,DOTY_KV:{get:async k=>records.get(k)||null,put:async(k,v)=>records.set(k,v),list:async()=>({keys:[],list_complete:true})}},ctx=(name='owner')=>({username:name,role:'admin',env:ownerEnvironment(env)});
 assert.equal(await ctx().env.DOTY_KV.get('data:owner'),JSON.stringify(owner));assert.equal(await ctx('other').env.DOTY_KV.get('data:other'),JSON.stringify(other));await assert.rejects(financeAccess(ctx(),{project_id:'old'},false),e=>e.status===503);
 const snapshot=await ownerBackupAccess(ctx());assert.equal(snapshot.payload.tracker.projects[0].notes,owner.data.projects[0].notes);let target=await B.create({...snapshot.payload.tracker,projects:snapshot.payload.tracker.projects.map(p=>({...p,notes:'Approved migration'}))},snapshot.payload.privateStores,'owner');const prepared=await ownerBackupAccess(ctx(),{action:'prepare',bundle:target,expected:await B.hash(snapshot.payload),operationId:'activation-first'}),oldRequest=ctx();await oldRequest.env.DOTY_KV.get('data:owner');await assert.rejects(oldRequest.env.DOTY_KV.put('data:owner',JSON.stringify(owner)),e=>e.status===409);
 // Old-version in-flight KV write: changed pre-activation source is detected.
 const changed=structuredClone(owner);changed.data.projects[0].notes='Legacy change before activation';changed.updatedAt='2026-10-02T01:00:00Z';records.set('data:owner',JSON.stringify(changed));await assert.rejects(ownerBackupAccess(ctx(),{action:'apply',token:prepared.token}),e=>e.status===409);assert.equal(await ctx().env.DOTY_KV.get('data:owner'),JSON.stringify(changed));await ownerBackupAccess(ctx(),{action:'cancel',token:prepared.token});await assert.rejects(ownerBackupAccess(ctx(),{action:'apply',token:prepared.token}),e=>e.status===409);await ctx().env.DOTY_KV.put('data:owner',JSON.stringify(changed));
 const latest=await ownerBackupAccess(ctx());target=await B.create({...latest.payload.tracker,projects:latest.payload.tracker.projects.map(p=>({...p,notes:'Approved migration'}))},latest.payload.privateStores,'owner');const ready=await ownerBackupAccess(ctx(),{action:'prepare',bundle:target,expected:await B.hash(latest.payload),operationId:'activation-approved'});await ownerBackupAccess(ctx(),{action:'apply',token:ready.token});assert.equal(JSON.parse(await ctx().env.DOTY_KV.get('data:owner')).data.projects[0].notes,'Approved migration');assert.deepEqual(JSON.parse(await ctx().env.DOTY_KV.get('data:owner')).data.projects[0].schedule[0].sharedWith,['*']);assert.equal((await ownerBackupAccess(ctx())).payload.tracker.projects[0].schedule[0].sharedWith,undefined);assert.equal(records.get('data:owner'),JSON.stringify(changed));assert.equal(await ctx('other').env.DOTY_KV.get('data:other'),JSON.stringify(other));await assert.rejects(oldRequest.env.DOTY_KV.put('data:owner',JSON.stringify(owner)),e=>e.status===409);const ledger=await financeAccess(ctx(),{project_id:'old'},false);assert.equal(ledger.rows.length,0);assert.equal((await ownerBackupAccess(ctx(),{action:'recovery',token:ready.token})).payload.tracker.projects[0].notes,'Legacy change before activation');console.log('PASS: existing KV visible until explicit owner restore, no other-user reset, pending migration fence/cancel, legacy change revalidation, atomic owner activation, old-request refusal and preserved KV/recovery.');
})().catch(e=>{console.error(e);process.exitCode=1});
