'use strict';
/* Versioned, secret-free account backup contract. Browser and server share it. */
(function(root){
 const FORMAT='doty-account-backup',VERSION=8,PARTS=['tracker','privateStores'];
 const clone=x=>JSON.parse(JSON.stringify(x));
 const secret=/^(password|passwordHash|salt|token|accessToken|refreshToken|mcpTokens|credentials|authorization|auth|apiKey|secret|session|users)$/i;
 const denyKeys=new Set(['__proto__','prototype','constructor']);
 function fail(message){throw Error(message);}
 function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
 async function hash(x){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(x))))).map(b=>b.toString(16).padStart(2,'0')).join('');}
 function clean(x){if(Array.isArray(x))return x.filter(v=>!v?.sharedFrom).map(clean);if(x&&typeof x==='object'){const result={};for(const [key,v]of Object.entries(x)){if(v!==undefined&&!secret.test(key)&&!denyKeys.has(key)&&!['sharedVirtual','broadcastTo','sharedWith','ownerPassword'].includes(key))result[key]=clean(v);}return result;}return x;}
 function assertSafe(x,depth=0){if(depth>40)fail('Backup nesting is too deep.');if(Array.isArray(x)){for(const v of x)assertSafe(v,depth+1);}else if(x&&typeof x==='object'){for(const [key,v]of Object.entries(x)){if(secret.test(key)||denyKeys.has(key))fail('Backup contains an unsafe or credential field: '+key);assertSafe(v,depth+1);}}}
 function tracker(input){if(!input||!Array.isArray(input.projects))fail('Missing projects[].');const data=clean(input);data.projects=input.projects.filter(p=>{if(!p||typeof p!=='object'||Array.isArray(p))fail('Invalid owned project record.');return !p.sharedVirtual;}).map(clean);data.timeEntries=clean(input.timeEntries||[]);data.settings=Object.fromEntries(Object.entries(clean(input.settings||{})).filter(([k])=>['timezone','calendarMode','autoArchiveHours'].includes(k)));data.view=['calendar','projects','labour','contacts','settings'].includes(input.view)?input.view:'calendar';data.calendarMode=['day','week','month'].includes(input.calendarMode)?input.calendarMode:'day';return data;}
 const storeId=s=>s.kind==='finance'?'finance:'+s.projectId:s.kind;
 const prefixes={finance:['row:','proposal:','proposal-history:','checkpoint:','phase:','audit:','operation:'],people:['person:','people-audit:','people-operation:'],contacts:['contact:','contact-audit:','contact-operation:']};
 const exactKeys={finance:['revision','phase-schema','account-currency','expense-defaults'],people:['people-revision'],contacts:['contact-revision']};
 // Minimum reader/replay contracts. Historical audits may omit ID, actor and
 // timestamps; their revision is required. Unknown extra source fields survive.
 const record=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
 const nonempty=v=>typeof v==='string'&&!!v.trim();
 const revision=v=>Number.isSafeInteger(v)&&v>=0;
 function stringList(v,label){if(!Array.isArray(v)||v.some(x=>typeof x!=='string'))fail('Invalid '+label+'.');}
 function optionalText(v,fields,label){for(const k of fields)if(v[k]!==undefined&&typeof v[k]!=='string')fail('Invalid '+label+' '+k+'.');}
 function optionalTimestamp(v,k,label){if(v[k]!==undefined&&(typeof v[k]!=='string'||!Number.isFinite(Date.parse(v[k]))))fail('Invalid '+label+' timestamp.');}
 function validateStoredRecord(key,value){
  const audit=/^(audit|people-audit|contact-audit):/.test(key),operation=/^(operation|people-operation|contact-operation):/.test(key);
  if(audit){if(!record(value)||!revision(value.revision))fail('Invalid audit record.');optionalText(value,['id','action','actor','channel'],'audit');for(const k of ['rowIds','proposalIds','phaseIds'])if(value[k]!==undefined)stringList(value[k],'audit '+k);optionalTimestamp(value,'at','audit');}
  if(operation){if(!record(value)||!nonempty(value.fingerprint)||!record(value.result)||!revision(value.result.revision))fail('Invalid operation receipt.');optionalText(value.result,['action','personId','contactId'],'operation result');if(key.startsWith('people-operation:')&&!nonempty(value.result.personId)||key.startsWith('contact-operation:')&&!nonempty(value.result.contactId))fail('Invalid directory operation result.');for(const k of ['rowIds','proposalIds','phaseIds','warnings'])if(value.result[k]!==undefined)stringList(value.result[k],'operation '+k);}
  if(key.startsWith('proposal:')||key.startsWith('proposal-history:')){if(!record(value)||!nonempty(value.id)||key.slice(key.indexOf(':')+1)!==value.id||!record(value.row))fail('Invalid proposal wrapper.');if(value.warnings!==undefined)stringList(value.warnings,'proposal warnings');optionalTimestamp(value,'createdAt','proposal');optionalTimestamp(value,'resolvedAt','proposal');if(key.startsWith('proposal-history:')&&!['accept','reject'].includes(value.resolution))fail('Invalid proposal resolution.');}
  if(key.startsWith('row:')||key.startsWith('proposal:')||key.startsWith('proposal-history:')){const row=key.startsWith('row:')?value:value.row;if(record(row)&&(typeof row.currency!=='string'||row.date!==undefined&&typeof row.date!=='string'))fail('Invalid financial currency/date.');if(!record(row)||!nonempty(row.id)||!record(row.provenance)||typeof row.provenance.reference!=='string'||typeof row.provenance.text!=='string')fail('Invalid financial source record.');optionalText(row.provenance,['sourceId','occurrence'],'provenance');optionalTimestamp(row,'createdAt','financial');if(row.voided!==undefined&&typeof row.voided!=='boolean')fail('Invalid financial void flag.');}
  if(key.startsWith('checkpoint:')){if(!record(value)||value.id!==key.slice(11)||!nonempty(value.id)||!['expenses','chargeableExpenses','billable','clientPayments','workerPay','workerPayouts'].includes(value.metric)||typeof value.currency!=='string'||!/^[A-Z]{3}$/.test(value.currency||''))fail('Invalid checkpoint.');root.DotyLedger.cents(value.amount);optionalText(value,['reference'],'checkpoint');for(const k of ['phase','phaseId'])if(value[k]!=null&&typeof value[k]!=='string')fail('Invalid checkpoint '+k+'.');if(value.throughDate!==undefined&&value.throughDate!==''&&!root.DotyLedger.validDate(value.throughDate))fail('Invalid checkpoint date.');}
  if(key==='expense-defaults'&&!record(value))fail('Invalid expense defaults.');
  if(key==='account-currency'&&value!==null&&(typeof value!=='string'||!/^[A-Z]{3}$/.test(value)))fail('Invalid account currency.');
  if(key.startsWith('person:')){if(!record(value)||value.wageHistory!==undefined&&!Array.isArray(value.wageHistory))fail('Invalid person history.');if(value.archived!==undefined&&typeof value.archived!=='boolean')fail('Invalid person archive flag.');for(const w of value.wageHistory||[]){if(!record(w)||!nonempty(w.id)||typeof w.currency!=='string'||typeof w.day!=='string'||typeof w.hour!=='string'||w.revision!==undefined&&!revision(w.revision))fail('Invalid wage history.');optionalTimestamp(w,'recordedAt','wage');}}
  if(key.startsWith('contact:')){if(!record(value))fail('Invalid contact.');optionalText(value,['name','company','contactPerson','phone','email','serviceArea','leadTime','notes'],'contact');stringList(value.categories,'contact categories');stringList(value.projectIds,'contact project IDs');if(value.archived!==undefined&&typeof value.archived!=='boolean')fail('Invalid contact archive flag.');}
 }
 function validateStore(s){if(!s||!prefixes[s.kind]||(s.kind==='finance'&&(typeof s.projectId!=='string'||!s.projectId||s.projectId.length>100)))fail('Invalid private store identity.');if(!Array.isArray(s.entries)||s.entries.length>50000)fail('Invalid private store entries.');const keys=new Set(),ids=new Set();for(const pair of s.entries){if(!Array.isArray(pair)||pair.length!==2||typeof pair[0]!=='string')fail('Invalid stored record.');const [key,value]=pair;if(keys.has(key))fail('Duplicate stored key.');keys.add(key);if(!exactKeys[s.kind].includes(key)&&!prefixes[s.kind].some(p=>key.startsWith(p)))fail('Unexpected private store field: '+key);assertSafe(value);validateStoredRecord(key,value);if(key==='phase-schema'&&(!Number.isSafeInteger(value)||value<0||value>1))fail('Invalid phase schema version.');if(key.startsWith('phase:')){if(!value||typeof value!=='object'||Array.isArray(value)||value.id!==key.slice(6)||!value.id||typeof value.name!=='string')fail('Invalid phase record.');root.DotyLedger.phaseName(value.name);}if(key==='expense-defaults')root.DotyLedger.expenseDefaults(value);if(key.endsWith('revision')&&(!Number.isSafeInteger(value)||value<0))fail('Invalid revision.');if(key.startsWith('row:')||key.startsWith('proposal:')||key.startsWith('proposal-history:')){const row=key.startsWith('row:')?value:value?.row;if(!row||typeof row.id!=='string')fail('Financial record needs stable ID.');if(key.startsWith('row:')&&key!=='row:'+row.id)fail('Financial key/ID mismatch.');root.DotyLedger.validate(row);if(key.startsWith('row:')){if(typeof row.createdAt!=='string'||!row.createdAt||!Number.isFinite(Date.parse(row.createdAt)))fail('Invalid financial creation timestamp.');if(ids.has(row.id))fail('Duplicate financial ID.');ids.add(row.id);}}if(key.startsWith('person:')){if(value?.id!==key.slice(7)||typeof value.name!=='string')fail('Invalid person.');root.DotyLedger.phaseName(value.name);for(const w of value.wageHistory||[]){if(!root.DotyLedger.validDate(w.effectiveDate)||!/^[A-Z]{3}$/.test(w.currency||'')||typeof w.id!=='string')fail('Invalid wage history.');if(w.day!=='')root.DotyLedger.cents(w.day);if(w.hour!=='')root.DotyLedger.cents(w.hour);}}if(key.startsWith('contact:')){if(value?.id!==key.slice(8)||!['supplier','subtrade'].includes(value.type)||!(value.name||value.company)||!Array.isArray(value.categories)||!Array.isArray(value.projectIds))fail('Invalid contact.');}}
 const rows=s.entries.filter(([k])=>k.startsWith('row:')).map(([,v])=>v);if(rows.length)root.DotyLedger.totals(rows);return s;}
 function validateTracker(data){assertSafe(data);if(!data||!Array.isArray(data.projects)||!Array.isArray(data.timeEntries)||data.projects.length>10000)fail('Invalid tracker backup.');const ids=new Set();for(const p of data.projects){if(!p||typeof p.id!=='string'||!p.id||typeof p.name!=='string'||ids.has(p.id)||p.sharedVirtual)fail('Invalid or duplicate owned project.');ids.add(p.id);if(p.notes!==undefined&&typeof p.notes!=='string')fail('Invalid project notes.');for(const k of ['schedule','todos','toBuy','archivedSchedule','archivedTodos','archivedToBuy'])if(p[k]!==undefined){if(!Array.isArray(p[k])||p[k].some(v=>!v||typeof v!=='object'||Array.isArray(v)))fail('Invalid '+k+' record.');}}if(data.timeEntries.some(v=>!v||typeof v!=='object'||Array.isArray(v)))fail('Invalid legacy time record.');return data;}
 function warnings(payload){const out=[];for(const s of payload.privateStores||[])for(const [key,value]of s.entries){const row=key.startsWith('row:')?value:value?.row;if(row?.currency&&row.currency!=='CAD')out.push('Unsupported '+row.currency+' financial source preserved; excluded from CAD totals.');if(key.startsWith('person:')&&(value.wageHistory||[]).some(w=>w.currency!=='CAD'))out.push('Unsupported wage history preserved; never used for CAD drafts.');}return [...new Set(out)];}
 async function create(trackerData,privateStores,owner){const payload={tracker:tracker(trackerData),privateStores:clean(privateStores)};validateTracker(payload.tracker);const identities=new Set();for(const s of payload.privateStores){validateStore(s);if(identities.has(storeId(s)))fail('Duplicate private store.');identities.add(storeId(s));}if(!identities.has('people')||!identities.has('contacts'))fail('Incomplete discovery: People and Contacts are required.');for(const p of payload.tracker.projects)if(!identities.has('finance:'+p.id))fail('Incomplete discovery: project '+p.name+' has no financial store snapshot.');const parts=await Promise.all(PARTS.map(async part=>({part,sha256:await hash(payload[part])})));return {format:FORMAT,version:VERSION,manifest:{complete:true,owner,createdAt:new Date().toISOString(),parts,stores:payload.privateStores.map(storeId).sort(),currency:'CAD'},payload};}
 async function validate(input){if(input?.format!==FORMAT){if(input&&Array.isArray(input.projects)){const data=tracker(input);validateTracker(data);return {legacy:true,tracker:data,warnings:['v7 tracker-only backup: no financial accounts, People or Contacts. Existing private stores will be preserved.']};}fail('Not a DOTY backup.');}if(input.version!==VERSION||input.manifest?.complete!==true||!input.payload)fail('Unsupported or incomplete backup manifest.');assertSafe(input);const {payload,manifest}=input;validateTracker(payload.tracker);if(!Array.isArray(payload.privateStores))fail('Missing private stores.');const stores=new Set();for(const s of payload.privateStores){validateStore(s);if(stores.has(storeId(s)))fail('Duplicate private store.');stores.add(storeId(s));}if(!stores.has('people')||!stores.has('contacts'))fail('Incomplete directories.');for(const p of payload.tracker.projects)if(!stores.has('finance:'+p.id))fail('Missing project financial store.');if(canonical([...stores].sort())!==canonical(manifest.stores))fail('Store inventory does not match manifest.');if(!Array.isArray(manifest.parts)||manifest.parts.length!==PARTS.length)fail('Incomplete part inventory.');for(const part of PARTS){const matches=manifest.parts.filter(p=>p.part===part);if(matches.length!==1||matches[0].sha256!==await hash(payload[part]))fail('Backup checksum mismatch: '+part);}return {legacy:false,bundle:clone(input),tracker:payload.tracker,warnings:warnings(payload)};}
 function summary(bundle){const p=bundle.payload,stores=p.privateStores;return {projects:p.tracker.projects.length,legacyHours:p.tracker.timeEntries.length,financeAccounts:stores.filter(s=>s.kind==='finance').length,acceptedOrVoided:stores.reduce((n,s)=>n+s.entries.filter(([k])=>k.startsWith('row:')).length,0),proposals:stores.reduce((n,s)=>n+s.entries.filter(([k])=>k.startsWith('proposal:')).length,0),people:stores.find(s=>s.kind==='people').entries.filter(([k])=>k.startsWith('person:')).length,contacts:stores.find(s=>s.kind==='contacts').entries.filter(([k])=>k.startsWith('contact:')).length};}
 const api={FORMAT,VERSION,canonical,hash,clean,tracker,storeId,validateStore,validateTracker,create,validate,summary,warnings};root.DotyBackup=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
