const assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');require('./ledger.js');const B=require('./backup.js');
(async()=>{
 const {FinanceAccount,financeAccess,peopleAccess,contactsAccess}=await import('./backend/finance-account.mjs'),{localNamespace}=await import('./backend/local-storage.mjs'),{LocalBackupService,recoverRestore}=await import('./backend/backup-local.mjs'),{accountBackupAccess}=await import('./backend/backup-account.mjs');const root=await fs.mkdtemp(path.join(os.tmpdir(),'doty-backup-'));const ns=localNamespace(FinanceAccount,{fileFor:name=>path.join(root,'.preview',Buffer.from(name).toString('base64url')+'.json')});
 const tracker={projects:[{id:'active',name:'Active synthetic',notes:'Original notes',schedule:[{id:'s',title:'Work',date:'2026-10-03'}],todos:[{id:'t',title:'Task'}],toBuy:[{id:'b',title:'Shopping'}],archivedSchedule:[{id:'as',title:'History',completed:true}]},{id:'archive',name:'Archived synthetic',archived:true,notes:'Retained archive'},{id:'shadow',name:'Shared',sharedVirtual:true,notes:'Other owner private view'}],timeEntries:[{id:'h',projectId:'active',date:'2026-10-03',hours:2.5,note:'Unassigned legacy'},{id:'old',projectId:'deleted',date:'2026-10-01',hours:1}],settings:{timezone:'America/Toronto',password:'never-export'},password:'secret',auth:{password:'secret'},view:'calendar',calendarMode:'week'};
 const ctx={username:'demo-owner',role:'admin',env:{ENABLE_FINANCE_REVIEW:'true',BACKUP_INDEX_COMPLETE:'true',FINANCE_ACCOUNTS:ns,DOTY_KV:{get:async k=>k==='data:demo-owner'?JSON.stringify({data:tracker}):null}}};const person=await peopleAccess(ctx,{action:'personAdd',name:'Synthetic worker',wageDay:'350',wageHour:'45',wageCurrency:'CAD',wageEffectiveDate:'2026-09-01',operationId:'backup-person-one',previousRevision:0});const personId=person.result.personId;await peopleAccess(ctx,{action:'personEdit',name:'Synthetic worker',personId,wageDay:'375',wageHour:'47.5',wageCurrency:'CAD',wageEffectiveDate:'2026-10-01',operationId:'backup-person-two',previousRevision:1});await peopleAccess(ctx,{action:'personArchive',personId,operationId:'backup-person-archive',previousRevision:2});await contactsAccess(ctx,{}, {action:'contactAdd',operationId:'backup-contact-one',previousRevision:0,contact:{type:'supplier',name:'Synthetic supplier',categories:['Tile'],projectIds:['active','archive'],notes:'Private synthetic contact'}});
 let revision=0;const mutate=async(action,extra)=>{const result=await financeAccess(ctx,{project_id:'active',mutation:{action,operationId:'backup-finance-'+crypto.randomUUID(),previousRevision:revision,...extra}},true,'browser');revision=result.ledger.revision;return result;};const phaseId=(await mutate('phaseAdd',{name:'Bathroom'})).result.phaseIds[0];const row={kind:'expense',phaseId,amount:'25.00',vendor:'Synthetic',category:'Materials',currency:'CAD',clientCharge:'atCost',date:'2026-10-03',provenance:{reference:'Receipt',text:'Synthetic purchase 25',sourceId:'receipt-1'}};const accepted=await mutate('add',{rows:[row]});await mutate('void',{rowId:accepted.result.rowIds[0],reason:'Synthetic review'});await mutate('stage',{rows:[{...row,amount:'30.00',provenance:{reference:'Pending receipt',text:'Synthetic pending expense 30',sourceId:'receipt-2'}}],checkpoints:[{currency:'CAD',metric:'expenses',amount:'30.00',reference:'Unverified total'}]});
 // Discover an orphan account from files even after project removal, without guessing IDs.
 const orphan=ns.get(JSON.stringify(['demo-owner','deleted'])).storage;await orphan.transaction(tx=>tx.put('revision',4));const service=new LocalBackupService({root,namespace:ns});const bundle=await service.export(tracker);const checked=await B.validate(bundle);assert.equal(checked.legacy,false);assert.equal(bundle.payload.tracker.projects.length,2);assert(!JSON.stringify(bundle).includes('secret'));assert(!JSON.stringify(bundle).includes('Other owner private'));assert(bundle.manifest.stores.includes('finance:deleted'));assert.deepEqual(B.summary(bundle),{projects:2,legacyHours:2,financeAccounts:3,acceptedOrVoided:1,proposals:1,people:1,contacts:1});const remote=await accountBackupAccess(ctx);assert.equal((await B.validate(remote)).legacy,false); // registered/current accounts, complete mandatory stores
 const tampered=structuredClone(bundle);tampered.payload.tracker.projects[0].notes='changed';await assert.rejects(B.validate(tampered),/checksum/);const partial=structuredClone(bundle);partial.manifest.complete=false;await assert.rejects(B.validate(partial),/incomplete/);const malicious=structuredClone(bundle);malicious.payload.tracker.auth={password:'x'};await assert.rejects(B.validate(malicious),/credential/);
 // Valid checksums cannot make malformed phases or null tracker records safe to restore.
 const beforeInvalid=(await service.export(tracker)).payload;
 for(const mutation of [b=>b.payload.privateStores.find(s=>s.kind==='finance').entries.push(['audit:malformed',null]),b=>b.payload.privateStores.find(s=>s.kind==='finance').entries.push(['operation:malformed',{fingerprint:'source',result:null}]),b=>b.payload.privateStores.find(s=>s.kind==='finance').entries.push(['phase:bad',{id:'bad'}]),b=>b.payload.privateStores.find(s=>s.kind==='finance').entries.push(['phase:bad',{id:'different',name:'Bad'}]),b=>{const s=b.payload.privateStores.find(s=>s.kind==='finance');s.entries=s.entries.filter(([k])=>k!=='phase-schema');s.entries.push(['phase-schema','1']);},b=>b.payload.tracker.projects[0].schedule.push(null),b=>b.payload.tracker.timeEntries.push(null),b=>{const s=b.payload.privateStores.find(s=>s.kind==='finance'&&s.entries.some(([k])=>k.startsWith('row:')));delete s.entries.find(([k])=>k.startsWith('row:'))[1].createdAt;}]){
  const bad=structuredClone(bundle);mutation(bad);for(const part of bad.manifest.parts)part.sha256=await B.hash(bad.payload[part.part]);await assert.rejects(service.prepare(bad,tracker,await service.currentDigest(tracker)),/Invalid/);assert.deepEqual((await service.export(tracker)).payload,beforeInvalid);
 }
 await assert.rejects(B.validate({projects:[{id:'v7',name:'Legacy',schedule:[null]}],timeEntries:[]}),/Invalid schedule/);await assert.rejects(B.validate({projects:[],timeEntries:[null]}),/Invalid legacy time/);
 const digest=await service.currentDigest(tracker),prepared=await service.prepare(bundle,tracker,digest);await orphan.transaction(tx=>tx.put('revision',5));await assert.rejects(service.apply(prepared.token,tracker),e=>e.status===409);const next=await service.prepare(bundle,tracker,await service.currentDigest(tracker));const result=await service.apply(next.token,tracker);assert.equal(result.status,'committed');assert((await service.apply(next.token,tracker)).replayed);const roundtrip=await service.export(result.tracker);for(const original of bundle.payload.privateStores){const restored=roundtrip.payload.privateStores.find(s=>B.storeId(s)===B.storeId(original));for(const [key,value]of original.entries){if(!key.endsWith('revision'))assert.deepEqual(new Map(restored.entries).get(key),value);}}assert.equal(result.tracker.projects[0].notes,'Original notes');assert.equal(result.tracker.projects[1].archived,true);assert.equal(result.tracker.timeEntries[0].hours,2.5);assert((await financeAccess(ctx,{project_id:'active'},false)).revision>revision);await assert.rejects(financeAccess(ctx,{project_id:'active',mutation:{action:'add',operationId:'stale-backup-write',previousRevision:revision,rows:[{...row,provenance:{reference:'New',text:'Synthetic',sourceId:'stale'}}]}},true),e=>e.status===409);
 const originalPayload=(await service.export(result.tracker)).payload;service.failAfter=2;const failure=await service.prepare(bundle,result.tracker,await service.currentDigest(result.tracker));await assert.rejects(service.apply(failure.token,result.tracker),/rolled back/);assert.deepEqual((await service.export(result.tracker)).payload,originalPayload);service.failAfter=null;
 const v7={projects:[{id:'converted',name:'V7 synthetic',notes:'Preserve every original note',schedule:[],todos:[],toBuy:[]}],timeEntries:[{project:'Unknown source',start:'2026-10-01T23:00:00Z',end:'2026-10-02T01:00:00Z',note:'Original legacy shape'}],settings:{},view:'today'};const legacy=await B.validate(v7);assert(legacy.legacy);assert.deepEqual(legacy.tracker.timeEntries,v7.timeEntries);const legacyPrepared=await service.prepare(v7,result.tracker,await service.currentDigest(result.tracker));const legacyResult=await service.apply(legacyPrepared.token,result.tracker);assert.equal(legacyResult.tracker.projects[0].notes,v7.projects[0].notes);const legacyExport=await service.export(legacyResult.tracker);assert.equal(B.summary(legacyExport).acceptedOrVoided,1);assert.equal(B.summary(legacyExport).people,1);assert.equal(B.summary(legacyExport).contacts,1);
 // Durable recovery occurs before stores are opened following process interruption.
 const file=path.join(root,'.preview','recovery-test.json');await fs.writeFile(file,JSON.stringify({after:true}));await fs.writeFile(service.file,JSON.stringify({status:'applying',before:[{file,entries:{before:true}}]}));await recoverRestore(root);assert.deepEqual(JSON.parse(await fs.readFile(file,'utf8')),{before:true});assert.equal(JSON.parse(await fs.readFile(service.file,'utf8')).status,'rolledBack');
 const foreign=structuredClone(bundle);foreign.manifest.owner='another-owner';await assert.rejects(service.prepare(foreign,legacyResult.tracker,await service.currentDigest(legacyResult.tracker)),e=>e.status===403);await assert.rejects(accountBackupAccess({...ctx,role:'user'}),e=>e.status===403);await fs.rm(root,{recursive:true,force:true});console.log('PASS: complete V8 inventory/checksums/privacy, archive and orphan discovery, all-store content roundtrip, revision fence/conflict, lost-response replay, partial failure rollback, crash recovery, v7 tracker-only conversion without inferred money/people/dates, role/owner isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
