const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const L=require('./ledger.js');
const base={currency:'CAD',phase:'Bathroom',date:'2026-09-01'};
const expense={...base,kind:'expense',vendor:'Demo',category:'Materials',amount:'120.50',clientCharge:'atCost',tax:'10.50'};
const labour={...base,kind:'labour',person:'Demo worker',unit:'days',quantity:'2.5',billRate:'500',payRate:'350'};
const rows=[expense,labour,{...base,kind:'clientPayment',amount:'1000'},{...base,kind:'workerPayout',person:'Demo worker',amount:'350'}];
assert.deepEqual([L.totals(rows).CAD.expenses,L.totals(rows).CAD.billable,L.totals(rows).CAD.accountBalance,L.totals(rows).CAD.workerOutstanding],[12050,125000,37050,52500]);
assert.equal(L.totals([...rows,{...expense,currency:'USD',amount:'2.01',tax:''}]).USD.expenses,201);
assert.equal(L.totals([{...expense,voided:true}]).CAD,undefined);
assert.equal(L.totals([{...labour,payRate:''}]).CAD.unknownPay,1);
assert.equal(L.totals([{...labour,unit:'hours'}]).CAD.billable,125000);
assert.equal(L.totals([labour,{...labour,date:''}]).CAD.billable,250000);
for(const bad of ['-1','1.001','NaN','Infinity','1e3'])assert.throws(()=>L.cents(bad));
assert.throws(()=>L.validate({...expense,tax:'121'}));assert.throws(()=>L.validate({...expense,date:'2026-02-30'}));
assert(L.warnings({...expense,provenance:{text:'Running total correction',reference:'line 2'}},[expense]).length>=3);
const memory=new Map();const ctx={DotyFinanceClient:require('./finance-client.js'),FINANCE_DEMO_SYNC:false,localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},sync:{user:null,viewAs:null},LOCAL_REVIEW:true,uid:()=>"fixture-phase",DotyLedger:L,window:{addEventListener:()=>{}},setInterval:()=>{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('ledger-ui.js','utf8'),ctx);
const p={id:'test'};const snap=ctx.financeRead(p);ctx.financeWrite(p,snap,{version:1,revision:0,rows:[],proposals:[]});assert.throws(()=>ctx.financeWrite(p,snap,snap.data),/Another tab/);
assert.equal(ctx.financeAllowed({...p,sharedVirtual:true}),false);ctx.sync.viewAs='other';assert.equal(ctx.financeAllowed(p),false);ctx.sync.viewAs=null;ctx.sync.user={role:'worker',username:'worker'};assert.equal(ctx.financeAllowed(p),false);
const html=fs.readFileSync('index.html','utf8');new vm.Script(html.match(/<script>\n([\s\S]*?)<\/script>/)[1]);assert(html.includes('JSON.stringify({ data: state, prevUpdatedAt: sync.lastRemoteAt })'));assert(!JSON.stringify(ctx.financeRead(p).data).includes('notes'));assert(html.includes('if(!LOCAL_REVIEW) initSync()'));
assert.equal(L.totals([{...expense,clientCharge:'none',purchasedBy:'client'}]).CAD.accountBalance,0);
assert.throws(()=>L.validate({...expense,purchasedBy:'client'}),/cannot be charged/);
const fractional={...labour,unit:'hours',quantity:'0.29',billRate:'0.50',payRate:'0.50'};
assert.equal(L.totals([fractional]).CAD.billable,15);assert.equal(L.totals([fractional]).CAD.workerPay,15);
assert.throws(()=>L.validate({...labour,quantity:'9'.repeat(400)}));
assert.throws(()=>L.totals([{...expense,amount:'90071992547409.91',tax:''},{...expense,amount:'0.02',tax:''}]),/too large/);
assert.throws(()=>L.totals([{...expense,amount:'90071992547409.91',tax:''},{...labour,quantity:'1',billRate:'0.01',payRate:''}]),/too large/);
for(const person of ['constructor','__proto__','toString']){const t=L.totals([{...labour,person}]).CAD;assert.equal(t.workers['legacy:'+person].earned,87500);assert(Object.hasOwn(t.workers,'legacy:'+person));}
assert.throws(()=>ctx.financeValidateLocalOperation({phases:[{id:'phase-bath',name:'Bathroom'}],rows:[{...expense,provenance:{sourceId:'source-1'}}],proposals:[{id:'q',row:{...expense,provenance:{sourceId:'source-1',reference:'fixture',text:'Demo'}}}]},{action:'accept',proposalId:'q',phaseId:'phase-bath'}),/already recorded/);
assert.throws(()=>ctx.financeValidateLocalOperation({phases:[{id:'phase-bath',name:'Bathroom'}],rows:[],proposals:[{id:'q',row:{...expense,provenance:{reference:'fixture',text:'Running total 120.50'}}}]},{action:'accept',proposalId:'q',phaseId:'phase-bath'}),/evidence only/);
assert.throws(()=>ctx.financeValidateLocalOperation({phases:[{id:'phase-bath',name:'Bathroom'}],rows:[],proposals:[{id:'q',row:{...expense,provenance:{reference:'fixture',text:'Correct previous purchase'}}}]},{action:'accept',proposalId:'q',phaseId:'phase-bath'}),/exact row ID/);
console.log('PASS: ledger math, currency separation, half-days/hours, unknown pay, voids, validation, review warnings, persistence conflicts, permission guards, script syntax, existing sync CAS, local preview isolation.');
