const assert=require('node:assert/strict');require('./ledger.js');
(async()=>{
 const {FinanceAccount}=await import('./backend/finance-account.mjs'),{localNamespace}=await import('./backend/local-storage.mjs');
 const ns=localNamespace(FinanceAccount),account=ns.get(ns.idFromName(JSON.stringify(['owner','synthetic']))),person={id:'synthetic-owner',name:'Owner'},row={id:'legacy-half-day',kind:'labour',date:'',phaseId:null,currency:'CAD',person:'Owner',personId:person.id,unit:'days',quantity:'0.5',billRate:'600.00',payRate:'',provenance:{reference:'Synthetic undated separate day',text:'Original half-day source',sourceId:'synthetic-source-half-day',occurrence:'separate-half-day'}};
 await account.storage.transaction(async tx=>{await tx.put('row:'+row.id,row);await tx.put('revision',1);await tx.put('phase-schema',1);await tx.put('phase:known',{id:'known',name:'Known phase'});});
 const read=async()=>account.fetch(new Request('https://finance.internal/review')).then(r=>r.json());
 const mutate=async mutation=>{const r=await account.fetch(new Request('https://finance.internal/mutate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actor:'owner',channel:'browser',directory:{people:[person]},mutation})}));return {status:r.status,body:await r.json()};};
 const input=(({id,...rest})=>rest)(row),op={action:'replace',rowId:row.id,reason:'Owner explicitly confirmed own earnings',operationId:'synthetic-earnings-correction',previousRevision:1,rows:[{...input,payRate:'600.00',correctionOf:row.id}]};
 const done=await mutate(op);assert.equal(done.status,200);let ledger=done.body.ledger,active=ledger.rows.find(r=>!r.voided);assert.equal(active.phaseId,null);assert.equal(active.date,'');assert.equal(active.quantity,'0.5');assert.equal(active.billRate,'600.00');assert.equal(active.payRate,'600.00');assert.deepEqual(active.provenance,row.provenance);assert.equal(active.replaces,row.id);assert.equal(ledger.rows.find(r=>r.id===row.id).voided,true);assert.equal(ledger.audit.at(-1).sourceRow,row.id);assert.equal(globalThis.DotyLedger.totals(ledger.rows).CAD.billable,30000);assert.equal(globalThis.DotyLedger.totals(ledger.rows).CAD.workerPay,30000);
 const replay=await mutate(op);assert.equal(replay.body.replayed,true);assert.equal(replay.body.ledger.rows.length,2);
 const before=JSON.stringify(await read());let bad=await mutate({action:'add',operationId:'synthetic-new-unassigned',previousRevision:2,rows:[{...input,provenance:{...input.provenance,sourceId:'new-source'}}]});assert.equal(bad.status,400);assert.match(bad.body.error,/Select a project phase/);assert.equal(JSON.stringify(await read()),before);
 bad=await mutate({action:'replace',rowId:active.id,reason:'Cannot invent old named phase',operationId:'synthetic-changed-phase',previousRevision:2,rows:[{...input,payRate:'600.00',phase:'Invented',correctionOf:active.id}]});assert.equal(bad.status,400);assert.equal(JSON.stringify(await read()),before);
 const assigned=await mutate({action:'add',operationId:'synthetic-assigned-booking',previousRevision:2,rows:[{...input,phaseId:'known',provenance:{...input.provenance,sourceId:'known-source'}}]});assert.equal(assigned.status,200);const assignedId=assigned.body.result.rowIds[0],assignedBefore=JSON.stringify(await read());bad=await mutate({action:'replace',rowId:assignedId,reason:'Cannot erase known phase',operationId:'synthetic-remove-known-phase',previousRevision:3,rows:[{...input,payRate:'600.00',provenance:{...input.provenance,sourceId:'known-source'},correctionOf:assignedId}]});assert.equal(bad.status,400);assert.equal(JSON.stringify(await read()),assignedBefore);
 const payout={kind:'workerPayout',date:'',phaseId:null,currency:'CAD',person:'Owner',personId:person.id,amount:'300.00',description:'Undated owner-confirmed project account settlement; no phase/payment method inferred.',provenance:{reference:'Synthetic owner confirmation',text:'Owner confirmed existing earnings paid',sourceId:'synthetic-owner-paid-confirmation'}};
 const paid=await mutate({action:'add',operationId:'synthetic-undated-owner-payout',previousRevision:3,rows:[payout]});assert.equal(paid.status,200);const paidRow=paid.body.ledger.rows.find(r=>r.id===paid.body.result.rowIds[0]);assert.equal(paidRow.date,'');assert.equal(paidRow.phaseId,null);assert.equal(globalThis.DotyLedger.totals(paid.body.ledger.rows).CAD.workerPayouts,30000);assert.equal(globalThis.DotyLedger.totals(paid.body.ledger.rows).CAD.billable,60000);
 const payoutReplay=await mutate({action:'add',operationId:'synthetic-undated-owner-payout',previousRevision:3,rows:[payout]});assert.equal(payoutReplay.body.replayed,true);assert.equal(globalThis.DotyLedger.totals(payoutReplay.body.ledger.rows).CAD.workerPayouts,30000);
 const payoutBefore=JSON.stringify(await read());const invalidPhase=await mutate({action:'add',operationId:'synthetic-payout-invalid-phase',previousRevision:4,rows:[{...payout,phaseId:'missing',provenance:{...payout.provenance,sourceId:'invalid-phase-source'}}]});assert.equal(invalidPhase.status,400);assert.equal(JSON.stringify(await read()),payoutBefore);
 console.log('PASS: historical unassigned phase preserved in audited/replay-safe correction; dates/half-days/client billing/source identities intact; new unassigned bookings, invented legacy phase and erasing known phase rejected atomically.');
})().catch(e=>{console.error(e);process.exitCode=1});
