const assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');require('./ledger.js');const B=require('./backup.js');
(async()=>{
 const {FinanceAccount,financeAccess,peopleAccess,contactsAccess}=await import('./backend/finance-account.mjs'),{localNamespace}=await import('./backend/local-storage.mjs'),{ownerEnvironment,ownerBackupAccess}=await import('./backend/owner-account.mjs'),{default:worker}=await import('./backend/worker-review.mjs');const root=await fs.mkdtemp(path.join(os.tmpdir(),'doty-owner-'));class CheckedAccount extends FinanceAccount{constructor(ctx,env){const transaction=ctx.storage.transaction.bind(ctx.storage);ctx.storage.transaction=fn=>transaction(tx=>{const put=tx.put;tx.put=async(k,v)=>{assert(new TextEncoder().encode(k).length<=2048,'Cloudflare key size');assert(new TextEncoder().encode(JSON.stringify(v)).length<=128*1024,'Cloudflare value size');return put(k,v);};return fn(tx);});super(ctx,env);}}let ns=localNamespace(CheckedAccount,{fileFor:name=>path.join(root,Buffer.from(name).toString('base64url')+'.json')});const records=new Map([['data:owner',JSON.stringify({data:{projects:[{id:'old-private',name:'Old namespace evidence'}],timeEntries:[]}})],['tracker','legacy global never auto-imported'],['users',JSON.stringify({owner:{role:'admin'},other:{role:'admin'}})],['mcp:synthetic',JSON.stringify({username:'owner'})]]);const originalRecords=structuredClone(records);const base=()=>({OWNER_ACCOUNT_MODE:'fresh-v8',ENABLE_FINANCE_REVIEW:'true',DOTY_PASSWORD:'synthetic-only',FINANCE_ACCOUNTS:ns,DOTY_KV:{get:async k=>records.get(k)||null,put:async(k,v)=>records.set(k,v),delete:async k=>records.delete(k),list:async()=>({keys:[],list_complete:true})}});const ctx=(owner='owner',role='admin')=>({username:owner,role,env:ownerEnvironment(base())});const full=async()=>ownerBackupAccess(ctx());let n=0;
 assert.equal((await full()).payload.tracker.projects.length,0);assert.deepEqual((await full()).manifest.stores,['contacts','people']);
 const mcp=async(name,args)=>{const r=await worker.fetch(new Request('https://synthetic.invalid/mcp',{method:'POST',headers:{authorization:'Bearer synthetic','content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:++n,method:'tools/call',params:{name,arguments:args}})}),base());return r.json();};assert((await mcp('add_project',{name:'Owner synthetic'})).result.content[0].text.includes('Created project'));const initial=await full(),projectId=initial.payload.tracker.projects[0].id;
 const change=async(action,extra)=>{const c=ctx(),read=await financeAccess(c,{project_id:projectId},false);return financeAccess(c,{project_id:projectId,mutation:{action,previousRevision:read.revision,operationId:'owner-finance-'+(++n),...extra}},true,'browser');};const phase=(await change('phaseAdd',{name:'Bathroom'})).result.phaseIds[0];const person=(await peopleAccess(ctx(),{action:'personAdd',name:'Private worker',wageDay:'350',wageHour:'',wageCurrency:'CAD',wageEffectiveDate:'2026-10-01',previousRevision:0,operationId:'owner-person-one'})).result.personId;await peopleAccess(ctx(),{action:'personArchive',personId:person,previousRevision:1,operationId:'owner-person-archive'});await contactsAccess(ctx(),{},{action:'contactAdd',operationId:'owner-contact-one',previousRevision:0,contact:{type:'supplier',name:'Private supplier',categories:['Tile'],projectIds:[projectId],notes:'Private contact notes'}});
 const expense={kind:'expense',phaseId:phase,currency:'CAD',date:'2026-10-01',amount:'1130.00',tax:'130.00',vendor:'Synthetic vendor',category:'Materials',clientCharge:'markup',provenance:{reference:'Synthetic receipt',text:'Synthetic expense',sourceId:'owner-synthetic-1'}};const added=await change('add',{rows:[expense]});assert.equal(added.ledger.rows[0].clientGross,'1299.50');await change('void',{rowId:added.result.rowIds[0],reason:'Review sample'});await change('stage',{rows:[{...expense,clientCharge:'atCost',provenance:{reference:'Pending source',text:'Synthetic pending',sourceId:'owner-synthetic-2'}}]});
 // Large Unicode tracker chunking, original sharing authorization retained in
 // active tracker but excluded from backup; no users/password/token/private peers.
 const c=ctx(),record=JSON.parse(await c.env.DOTY_KV.get('data:owner'));record.data.projects[0].notes='Synthetic notes 🧱'.repeat(12000);record.data.projects[0].todos=[{id:'shared-task',title:'Shared task',sharedWith:['other']}];await c.env.DOTY_KV.put('data:owner',JSON.stringify(record));const bundle=await full();await B.validate(bundle);assert(bundle.payload.tracker.projects[0].notes.length>128000);assert(!JSON.stringify(bundle).includes('sharedWith'));assert(!JSON.stringify(bundle).includes('Old namespace evidence'));assert(!JSON.stringify(bundle).includes('synthetic-only'));assert.equal(B.summary(bundle).people,1);assert.equal(B.summary(bundle).contacts,1);await assert.rejects(ownerBackupAccess(ctx('owner','user')),e=>e.status===403);assert.equal(B.summary(await ownerBackupAccess(ctx('other'))).people,0);
 const prepare=async(bundle,token)=>ownerBackupAccess(ctx(),{action:'prepare',bundle,expected:await B.hash((await full()).payload),operationId:token});const apply=token=>ownerBackupAccess(ctx(),{action:'apply',token});const target=structuredClone(bundle);target.payload.tracker.projects[0].notes='Restored complete source notes';target.payload.privateStores.find(s=>s.kind==='finance').entries.push(['audit:historical',{revision:0,action:'legacy'}]);for(const part of target.manifest.parts)part.sha256=await B.hash(target.payload[part.part]);
 const staleRequest=ctx();await staleRequest.env.DOTY_KV.get('data:owner');const p=await prepare(target,'owner-restore-first');assert.equal((await ownerBackupAccess(ctx(),{action:'status',token:p.token})).status,'prepared');assert.equal((await full()).payload.tracker.projects[0].notes,bundle.payload.tracker.projects[0].notes);const result=await apply(p.token);assert.equal(result.status,'committed');assert.equal((await apply(p.token)).replayed,true);assert.equal((await ownerBackupAccess(ctx(),{action:'prepare',bundle:target,expected:await B.hash(bundle.payload),operationId:p.token})).replayed,true);assert.equal((await ownerBackupAccess(ctx(),{action:'recovery',token:p.token})).payload.tracker.projects[0].notes,bundle.payload.tracker.projects[0].notes);await assert.rejects(peopleAccess(staleRequest,{action:'personRestore',personId:person,previousRevision:2,operationId:'pre-restore-worker'}),e=>e.status===409);
 const restored=await full();assert.equal(restored.payload.tracker.projects[0].notes,'Restored complete source notes');for(const s of target.payload.privateStores){const map=new Map(restored.payload.privateStores.find(t=>B.storeId(t)===B.storeId(s)).entries);for(const [k,v]of s.entries)if(!k.endsWith('revision'))assert.deepEqual(map.get(k),v);}assert.equal((await financeAccess(ctx(),{project_id:projectId},false)).proposals.length,1);
 // Checksums do not make malformed audit/replay/proposal/checkpoint records
 // safe. Reject before journal replacement or account writes; recovery survives.
 const retained=await prepare(target,'owner-review-retained'),beforeInvalid=(await full()).payload,recoveryBefore=await ownerBackupAccess(ctx(),{action:'recovery',token:p.token});let invalidIndex=0;
 const malformed=[['finance','audit:malformed',null],['finance','audit:malformed',[]],['finance','audit:malformed',{revision:'1'}],['finance','audit:malformed',{revision:-1}],['finance','audit:malformed',{revision:1.5}],['finance','audit:malformed',{revision:1,action:{}}],['people','people-audit:malformed',null],['contacts','contact-audit:malformed',null],['finance','operation:malformed',null],['finance','operation:malformed',{fingerprint:'source',result:null}],['finance','operation:malformed',{fingerprint:'source',result:{revision:'1'}}],['finance','operation:malformed',{fingerprint:'source',result:{revision:1,rowIds:[null]}}],['people','people-operation:malformed',{fingerprint:'source',result:{revision:1}}],['contacts','contact-operation:malformed',{fingerprint:'source',result:{revision:1,contactId:{}}}],['finance','proposal:malformed',null],['finance','proposal:malformed',{id:'different',row:expense}],['finance','proposal-history:malformed',{id:'malformed',row:{...expense,id:'row-malformed'},resolution:'maybe'}],['finance','checkpoint:malformed',null],['finance','checkpoint:malformed',{id:'malformed',currency:'CAD',metric:'invented',amount:'0'}],['people','person:malformed',{id:'malformed',name:'Bad',wageHistory:[null]}],['contacts','contact:malformed',{id:'malformed',type:'supplier',name:{},categories:[],projectIds:[]}],['contacts','contact:malformed',{id:'malformed',type:'supplier',name:'Bad',categories:[null],projectIds:[]}]];
 for(const [kind,key,value]of malformed){const bad=structuredClone(target);bad.payload.privateStores.find(s=>s.kind===kind).entries.push([key,value]);for(const part of bad.manifest.parts)part.sha256=await B.hash(bad.payload[part.part]);const operationId='owner-malformed-'+(++invalidIndex);await assert.rejects(prepare(bad,operationId),/Invalid/);await assert.rejects(apply(operationId),e=>e.status===404);assert.deepEqual((await full()).payload,beforeInvalid);assert.equal((await ownerBackupAccess(ctx(),{action:'status',token:retained.token})).status,'prepared');assert.deepEqual(await ownerBackupAccess(ctx(),{action:'recovery',token:p.token}),recoveryBefore);await financeAccess(ctx(),{project_id:projectId},false);}
 // Failed mid-transaction write and process reconstruction: no partial store,
 // tracker, inventory or success receipt can escape a failed commit.
 const p2=await prepare(bundle,'owner-restore-failure'),ownerDO=ns.get(JSON.stringify({kind:'owner-v8',owner:'owner'})),storage=ownerDO.storage,transaction=storage.transaction.bind(storage);storage.transaction=fn=>transaction(async tx=>{const put=tx.put;let writes=0;tx.put=async(...args)=>{await put(...args);if(++writes===5)throw Error('Injected interruption before commit');};return fn(tx);});await assert.rejects(apply(p2.token),/Injected interruption/);storage.transaction=transaction;assert.deepEqual((await full()).payload,restored.payload);assert.equal((await ownerBackupAccess(ctx(),{action:'status',token:p2.token})).status,'prepared');ns=localNamespace(CheckedAccount,{fileFor:name=>path.join(root,Buffer.from(name).toString('base64url')+'.json')});assert.deepEqual((await full()).payload,restored.payload);const committed=await apply(p2.token);assert.equal(committed.status,'committed');await assert.rejects(apply(p.token),e=>e.status===410);
 const concurrent=await prepare(target,'owner-restore-conflict');await peopleAccess(ctx(),{action:'personRestore',personId:person,previousRevision:(await peopleAccess(ctx())).revision,operationId:'concurrent-person-restore'});await assert.rejects(apply(concurrent.token),e=>e.status===409);assert.equal((await peopleAccess(ctx())).people[0].archived,false);
 // Export and a mutation race: both serial orders produce one coherent valid
 // account, and no other owner or credential data enters the export.
 const [raced]=await Promise.all([full(),change('phaseRename',{phaseId:phase,name:'Bathroom renamed'})]);await B.validate(raced);
 // V7 is explicitly tracker-only, with orphan private accounts retained and no
 // fabricated financial rows/people/rates. Same atomic coordinator boundary.
 const v7={projects:[{id:'v7',name:'Legacy synthetic',notes:'Original raw notes',schedule:[],todos:[],toBuy:[]}],timeEntries:[{project:'Unmatched original',start:'2026-10-01T10:00:00Z',end:'2026-10-01T12:00:00Z',note:'Raw legacy'}]};const legacy=await prepare(v7,'owner-restore-legacy');await apply(legacy.token);const afterLegacy=await full();assert(afterLegacy.manifest.stores.includes('finance:'+projectId));assert.deepEqual(afterLegacy.payload.tracker.timeEntries,v7.timeEntries);assert.equal(B.summary(afterLegacy).people,1);assert.equal(B.summary(afterLegacy).contacts,1);
 // Real authenticated public REST path, not only direct coordinator helpers.
 const salt='synthetic-salt',password='synthetic-pass',hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(salt+password)))).map(v=>v.toString(16).padStart(2,'0')).join('');records.set('users',JSON.stringify({owner:{role:'admin',salt,hash},other:{role:'user',salt,hash}}));const api=async(url,method='GET',body=null,username='owner')=>worker.fetch(new Request('https://synthetic.invalid'+url,{method,headers:{authorization:'Basic '+Buffer.from(username+':'+password).toString('base64'),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),base());
 assert.equal((await api('/account/backup','POST',{action:'export',owner:'other'})).status,400);const restExport=await (await api('/account/backup')).json();await B.validate(restExport);assert.equal((await api('/account/backup?as=other')).status,403);assert.equal((await api('/account/backup','GET',null,'other')).status,403);const trackerAPI=await (await api('/data')).json();const replacements=await Promise.all([api('/data','PUT',{data:trackerAPI.data,prevUpdatedAt:trackerAPI.updatedAt}),api('/data','PUT',{data:trackerAPI.data,prevUpdatedAt:trackerAPI.updatedAt})]);assert.deepEqual(replacements.map(r=>r.status).sort(),[200,409]);const successful=await replacements.find(r=>r.status===200).json();assert.equal(successful.updatedAt,(await (await api('/data')).json()).updatedAt);assert.equal((await api('/data','PUT',{data:trackerAPI.data})).status,409);assert.equal((await api('/data','PUT',{data:trackerAPI.data,prevUpdatedAt:null})).status,409);
 const apiBundle=await (await api('/account/backup')).json(),apiPrepare=await api('/account/backup','POST',{action:'prepare',bundle:apiBundle,expected:await B.hash(apiBundle.payload),operationId:'owner-rest-public'});assert.equal(apiPrepare.status,200);const apiToken=(await apiPrepare.json()).token;assert.equal((await api('/account/backup','POST',{action:'apply',token:apiToken})).status,200);assert.equal((await (await api('/account/backup','POST',{action:'status',token:apiToken})).json()).status,'committed');assert.equal((await (await api('/account/backup','POST',{action:'apply',token:apiToken})).json()).replayed,true);assert.equal((await api('/owner-backup','POST',{action:'export',owner:'other'})).status,404);
 // Paged inventory includes more than one Cloudflare list page.
 const ownerStorage=ns.get(JSON.stringify({kind:'owner-v8',owner:'owner'})).storage;await ownerStorage.transaction(async tx=>{for(let i=0;i<1005;i++)await tx.put('owned-store:'+encodeURIComponent('finance:'+projectId)+':audit:paged-'+String(i).padStart(4,'0'),{id:'paged-'+i,revision:i,action:'syntheticTest'});});const paged=await full();assert.equal(paged.payload.privateStores.find(s=>s.projectId===projectId).entries.filter(([k])=>k.startsWith('audit:paged-')).length,1005); // Execute the real remote backup screen handlers against the authenticated
 // Worker, including an intentionally lost apply response and resume path.
 const vm=require('node:vm'),local=new Map(),elements={},requests=[];const uiTracker=await (await api('/data')).json();local.set('tracker',JSON.stringify(uiTracker.data));const ui=vm.createContext({DotyBackup:B,FINANCE_DEMO_SYNC:false,LOCAL_REVIEW:false,financeRemote:()=>true,WORKER_URL:'https://synthetic.invalid',authHeader:()=> 'Basic '+Buffer.from('owner:'+password).toString('base64'),sync:{user:{username:'owner'},viewAs:null,inflight:false,lastRemoteAt:uiTracker.updatedAt},state:structuredClone(uiTracker.data),view:'settings',calendarMode:'day',openProjectId:null,STORE_KEY:'tracker',structuredClone,crypto,Date,JSON,setTimeout,clearTimeout,financeTransport:{cache:new Map()},peopleTransport:{cache:new Map()},contactsTransport:{cache:new Map()},escapeHtml:s=>String(s),toast:()=>{},render:opts=>{assert.equal(opts.storageRefresh,true);assert.equal(opts.restoring,true);},document:{getElementById:id=>elements[id]||=( {innerHTML:'',textContent:'',disabled:id==='backupApply'})},localStorage:{get length(){return local.size;},key:i=>[...local.keys()][i],getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},fetch:async(url,opts)=>{requests.push({url,opts});const response=await worker.fetch(new Request(url,opts),base());if(opts?.body&&JSON.parse(opts.body).action==='apply'&&ui.loseResponse){ui.loseResponse=false;throw Error('Synthetic response loss');}return response;}});vm.runInContext(await fs.readFile('backup-ui.js','utf8'),ui);const uiBundle=await ui.completeBackup(),uiTarget=await B.create({...uiBundle.payload.tracker,projects:uiBundle.payload.tracker.projects.map(p=>({...p,notes:'Remote UI restored notes'}))},uiBundle.payload.privateStores,'owner');const input={target:{files:[{size:JSON.stringify(uiTarget).length,text:async()=>JSON.stringify(uiTarget)}],value:'synthetic'}};await ui.importData(input);assert.equal(elements.backupApply.disabled,true);assert.notEqual(ui.state.projects[0].notes,'Remote UI restored notes');elements.backupConfirm.onchange({target:{checked:true}});ui.loseResponse=true;await elements.backupApply.onclick();assert(elements.backupStatus.textContent.includes('Synthetic response loss'));assert(local.has('doty.backup.recovery.v8'));await ui.resumeBackupRestore();assert.equal(ui.state.projects[0].notes,'Remote UI restored notes');assert.equal(local.has('doty.backup.recovery.v8'),false);assert.equal(ui.sync.lastRemoteAt,(await (await api('/data')).json()).updatedAt);assert(requests.some(r=>r.url.endsWith('/account/backup')&&r.opts.method==='POST'));assert(requests.every(r=>r.opts.headers.authorization.startsWith('Basic ')));records.set('users',originalRecords.get('users'));
 const foreign=structuredClone(target);foreign.manifest.owner='other';await assert.rejects(prepare(foreign,'owner-cross-owner'),e=>e.status===403);const invalid=structuredClone(target);invalid.payload.privateStores.find(s=>s.kind==='finance').entries.push(['phase:broken',{id:'broken'}]);for(const part of invalid.manifest.parts)part.sha256=await B.hash(invalid.payload[part.part]);await assert.rejects(prepare(invalid,'owner-invalid-phase'),/Invalid phase/);assert.deepEqual(records,originalRecords);await fs.rm(root,{recursive:true,force:true});console.log('PASS: fresh owner Worker/MCP shared routing, complete authoritative inventory/export, Unicode chunking, all-store atomic restore/recovery/replay, pre-restore request fences, rollback and restart, stale/concurrent conflict, coherent export race, V7 orphan preservation, owner/role/credential privacy, untouched legacy KV.');
})().catch(e=>{console.error(e);process.exitCode=1});
