const assert=require('node:assert/strict');const fs=require('node:fs');const L=require('./ledger.js');
(async()=>{
 const {FinanceAccount,financeAccess,peopleAccess,callFinanceTool}=await import('./backend/finance-account.mjs');const {localNamespace}=await import('./backend/local-storage.mjs');
 const namespace=localNamespace(FinanceAccount),original={projects:[{id:'one',notes:'Synthetic original notes'},{id:'two'}],timeEntries:[{id:'legacy-hour',projectId:'one',date:'2026-09-01',hours:2.5,note:'Synthetic overlapping hours'}]};
 const ctx={username:'owner',role:'admin',env:{ENABLE_FINANCE_REVIEW:'true',FINANCE_ACCOUNTS:namespace,DOTY_KV:{get:async k=>k==='data:owner'?JSON.stringify({data:original}):null}}};
 const read=id=>financeAccess(ctx,{project_id:id},false);let n=0;const change=async(id,action,fields)=>financeAccess(ctx,{project_id:id,mutation:{action,previousRevision:(await read(id)).revision,operationId:'people-finance-'+(++n),...fields}},true,'browser');
 const added=await callFinanceTool('add_account_person',{name:'  Demo   Worker ',operation_id:'people-add-first',previous_revision:0},ctx),personId=added.result.personId;
 assert.equal(added.ledger.people[0].name,'Demo Worker');assert.equal((await peopleAccess(ctx)).revision,1);
 assert.equal((await callFinanceTool('add_account_person',{name:'  Demo   Worker ',operation_id:'people-add-first',previous_revision:0},ctx)).replayed,true);
 await assert.rejects(peopleAccess(ctx,{action:'personAdd',name:'demo worker',previousRevision:1,operationId:'people-duplicate'}),/already exists/);
 await assert.rejects(peopleAccess(ctx,{action:'personAdd',personId,name:'demo worker',previousRevision:1,operationId:'people-bypass-id'}),/not allowed/);
 await assert.rejects(peopleAccess({...ctx,role:'user'}),e=>e.status===403);assert.equal((await peopleAccess({...ctx,username:'other',role:'manager'})).people.length,0);
 const race=await Promise.allSettled(['Person A','Person B'].map((name,i)=>peopleAccess(ctx,{action:'personAdd',name,previousRevision:1,operationId:'people-race-'+i})));assert.equal(race.filter(x=>x.status==='fulfilled').length,1);assert.equal(race.find(x=>x.status==='rejected').reason.status,409);
 const phases={};for(const id of ['one','two']){phases[id]=(await change(id,'phaseAdd',{name:'Main'})).result.phaseIds[0];await change(id,'currencySet',{currency:'CAD'});}
 const labour=id=>({kind:'labour',phaseId:phases[id],personId,currency:'CAD',date:'2026-09-01',unit:'days',quantity:'0.5',billRate:'600.00',payRate:'350.00',provenance:{reference:'Synthetic '+id,text:'Half day worked',sourceId:'synthetic-day-'+id}});
 const first=await change('one','add',{rows:[labour('one')]});const second=await change('two','add',{rows:[{...labour('two'),unit:'hours',quantity:'2.5',billRate:'80.00',payRate:'45.00'}]});
 assert.equal(first.ledger.rows[0].person,'Demo Worker');assert.equal(first.ledger.totals.CAD.billable,30000);assert.equal(second.ledger.totals.CAD.billable,20000);
 const directory=await peopleAccess(ctx);await callFinanceTool('edit_account_person',{person_id:personId,name:'Renamed Worker',operation_id:'people-edit-name',previous_revision:directory.revision},ctx);
 for(const id of ['one','two']){const d=await read(id);assert.equal(d.people.find(p=>p.id===personId).name,'Renamed Worker');assert.equal(d.rows[0].person,'Demo Worker');assert.equal(d.rows[0].personId,personId);assert.equal(d.rows[0].payRate,id==='one'?'350.00':'45.00');assert.equal(L.personLabel(d,d.rows[0]),'Renamed Worker');}
 const stable=JSON.stringify((await read('one')).totals);await assert.rejects(change('one','currencySet',{currency:'USD'}),/CAD only/);assert.equal(JSON.stringify((await read('one')).totals),stable);
 await assert.rejects(change('one','add',{rows:[{...labour('one'),currency:'USD',provenance:{reference:'Synthetic wrong currency',text:'Half day',sourceId:'wrong-currency'}}]}),/CAD only/);
 await assert.rejects(change('two','add',{rows:[{...labour('two'),personId:'other-owner-id'}]}),/Unknown person ID/);
 await assert.rejects(change('two','add',{rows:[{...labour('two'),personId:undefined,person:'Typo worker'}]}),/Select an account person/);
 const proposed=await change('two','stage',{rows:[{...labour('two'),personId:'foreign',person:'Unmatched source name',currency:'EUR',provenance:{reference:'Synthetic source',text:'Half day',sourceId:'import-person'}}]});assert.equal(proposed.ledger.proposals[0].row.personId,null);assert.equal(proposed.ledger.proposals[0].row.sourcePersonId,'foreign');
 await assert.rejects(change('two','accept',{proposalId:proposed.result.proposalIds[0],confirmed:true,phaseId:phases.two,personId}),/Unsupported non-CAD/);assert.equal((await read('two')).proposals[0].row.currency,'EUR');
 // Existing unassigned rows keep their original record; grouping needs an explicit assignment.
 const object=namespace.get(namespace.idFromName(JSON.stringify(['owner','two'])));await object.storage.transaction(tx=>tx.put('row:legacy-pay',{id:'legacy-pay',kind:'workerPayout',person:'Legacy spelling',currency:'CAD',amount:'25.00',phaseId:phases.two,date:'',createdAt:'2026-09-01T00:00:00Z',provenance:{reference:'Synthetic payout',text:'Paid worker'}}));
 const prior=(await read('two')).totals.CAD;const assigned=await change('two','personAssign',{rowId:'legacy-pay',personId});assert.equal(assigned.ledger.totals.CAD.workerPayouts,prior.workerPayouts);assert.equal(assigned.ledger.rows.find(r=>r.id==='legacy-pay').person,'Legacy spelling');assert.equal(assigned.ledger.totals.CAD.workers['id:'+personId].paid,2500);
 const collision=L.totals([{...labour('one'),person:'Legacy label'},{...labour('one'),personId:undefined,person:'id:'+personId}]);assert.equal(Object.keys(collision.CAD.workers).length,2);
 assert.deepEqual(original.timeEntries,[{id:'legacy-hour',projectId:'one',date:'2026-09-01',hours:2.5,note:'Synthetic overlapping hours'}]);assert.equal((await read('one')).totals.CAD.billable,30000);assert(!JSON.stringify(await peopleAccess(ctx)).includes('payRate'));
 const index=fs.readFileSync('index.html','utf8'),ui=fs.readFileSync('ledger-ui.js','utf8'),people=fs.readFileSync('people-ui.js','utf8');assert(index.includes('render({storageRefresh:true})'));assert(index.includes('if(!storageRefresh) save()'));assert(!index.includes('<button data-view="time">'));assert(index.includes('<button data-view="labour">'));assert(people.includes('Legacy hours'));assert(people.includes('No person, billing rate, pay rate or day conversion is inferred'));assert(ui.includes('type="hidden" name="currency"'));assert(ui.includes('select name="personId"'));assert(!ui.includes("field('person','Person')"));
 console.log('PASS: account People across projects, normalized duplicates/bypass, CAS/retry, owner privacy, stable rename IDs and source/rate snapshots, hours versus days, legacy overlap isolation, explicit unassigned import/assignment, inherited currency and retained foreign rows, Labour navigation/legacy read access.');
})().catch(e=>{console.error(e);process.exitCode=1});
