'use strict';
function peopleKey(){return 'doty.people.v1:'+(LOCAL_REVIEW?'review':sync.user?.username||'offline');}
const peopleTransport=new DotyFinanceClient({storage:localStorage,newId:()=>crypto.randomUUID(),request:async(_,mutation)=>{
 if(!financeRemote())throw Error('People sync unavailable.');if(!FINANCE_DEMO_SYNC&&(!sync.user||sync.viewAs))throw Error('Open your own account.');
 const response=await fetch(FINANCE_DEMO_SYNC?'/local-finance/people':WORKER_URL+'/finance/people',{method:mutation?'POST':'GET',headers:{'content-type':'application/json',...(!FINANCE_DEMO_SYNC?{authorization:authHeader()}:{})},cache:'no-store',...(mutation?{body:JSON.stringify({mutation})}:{})});const value=await response.json();if(!response.ok){const e=Error(value.error||'People request failed');e.status=response.status;throw e;}return value;
}});
function peopleRead(){if(financeRemote())return peopleTransport.cache.get(peopleKey())||{version:1,revision:0,people:[],rows:[],proposals:[],audit:[]};const raw=localStorage.getItem(peopleKey());return raw?JSON.parse(raw):{version:1,revision:0,people:[],rows:[],proposals:[],audit:[]};}
function wageFields(){return '<label>Worker wage per day<input name="wageDay" type="number" min="0" step="0.01" placeholder="Not set"></label><label>Worker wage per hour<input name="wageHour" type="number" min="0" step="0.01" placeholder="Not set"></label><input type="hidden" name="wageCurrency" value="CAD"><label>Effective from<input name="wageEffectiveDate" type="date"></label><div class="hint wide">Optional wage schedule. Enter an effective date with wages. Dollar amounts are CAD. Blank day/hour rates remain unknown; no conversion. A change on the same date preserves the previous schedule and supersedes it for new drafts. Client billing stays in the project.</div>';}
function personFormOperation(form,action,personId){const op={action,name:form.elements.name.value,...(personId?{personId}:{})};const values=Object.fromEntries(['wageDay','wageHour','wageCurrency','wageEffectiveDate'].map(k=>[k,form.elements[k].value]));if([values.wageDay,values.wageHour,values.wageEffectiveDate].some(Boolean))Object.assign(op,values);return op;}
async function peopleChange(op){if(financeRemote())return peopleTransport.mutate(peopleKey(),null,peopleRead().revision,op);const raw=localStorage.getItem(peopleKey()),d=peopleRead(),editing=['personAdd','personEdit'].includes(op.action),name=editing?DotyLedger.phaseName(op.name):null,wages=editing?DotyLedger.personWages(op):{};if(editing&&d.people.some(p=>DotyLedger.phaseKey(p.name)===DotyLedger.phaseKey(name)&&p.id!==op.personId))throw Error('A person with this name already exists (case/spacing ignored).');const p=op.action==='personAdd'?{id:uid()}:d.people.find(p=>p.id===op.personId);if(!p)throw Error('Person not found.');if(op.action==='personAdd'){if(d.people.length>=500)throw Error('Maximum 500 people.');d.people.push(p);}const previous=structuredClone(p);if(editing){p.name=name;if(Object.keys(wages).length){const history=p.wageHistory||[],prior=history.filter(w=>w.currency===wages.wageCurrency&&w.effectiveDate===wages.wageEffectiveDate).sort((a,b)=>b.revision-a.revision)[0];const day=wages.wageDay??'',hour=wages.wageHour??'';if(!prior||prior.day!==day||prior.hour!==hour)p.wageHistory=history.concat({id:uid(),effectiveDate:wages.wageEffectiveDate,currency:wages.wageCurrency,day,hour,revision:d.revision+1,recordedAt:new Date().toISOString(),...(prior?{supersedes:prior.id}:{})});}}else p.archived=op.action==='personArchive';d.revision++;d.audit.push({id:uid(),revision:d.revision,action:op.action,personId:p.id,previous,person:structuredClone(p),at:new Date().toISOString()});if(localStorage.getItem(peopleKey())!==raw)throw Error('People changed in another tab. Refresh and review.');localStorage.setItem(peopleKey(),JSON.stringify(d));}
async function renderLabour(){
 const targetView=view;app.innerHTML='<div class="h1">Labour</div><div class="hint">Loading account people…</div>';
 if(financeRemote()&&financeAllowed({})){try{await peopleTransport.load(peopleKey(),null);}catch(e){if(view===targetView)app.innerHTML=`<div class="h1">Labour</div><div class="err">${escapeHtml(e.message)}</div><button id="peopleRefresh">Retry</button>`;const r=document.getElementById('peopleRefresh');if(r)r.onclick=renderLabour;return;}}
 if(view!==targetView||openProjectId)return;
 const d=peopleRead(),esc=escapeHtml,allowed=financeAllowed({});
 app.innerHTML=`<div class="h1">Labour</div><div class="hint">Record labour in its project account. Days and hours stay separate; legacy hours are never included in bills automatically.</div><div class="finance-toolbar"><button id="managePeople">Manage people</button><button id="legacyHours">Legacy hours · read only (${state.timeEntries.length})</button></div><div class="h2">Project labour</div>${state.projects.filter(p=>!p.archived&&financeAllowed(p)).map(p=>`<div class="finance-row"><b>${esc(p.name)}</b><button data-labour-project="${esc(p.id)}">Open labour</button></div>`).join('')||'<div class="empty">No private project accounts available.</div>'}${allowed?`<section id="accountPeople" class="proj-section people-manager"><div class="h2">People · all projects</div><div class="hint">Your account directory, shared across your projects. Private wage defaults by date, used only for new drafts. Existing entry rates never change. Adding a person does not create a login or grant access; client billing stays in each project.</div><button id="peopleRefresh">Refresh people</button>${peopleTransport.pending(peopleKey())?'<div class="finance-warning">A People edit is awaiting confirmation. Refresh and review before retrying or discarding.<button id="peopleRetry">Retry edit</button><button id="peopleDiscard">Discard pending intent</button></div>':''}<form id="peopleAdd" class="finance-form"><label>New person name<input name="name" maxlength="120" required autocomplete="off"></label>${wageFields()}<div class="finance-toolbar"><button>Add person</button><button type="button" id="peopleCancel">Cancel</button></div></form><div class="err" id="peopleError" role="alert"></div>${d.people.map(p=>`<div class="finance-row"><b>${esc(p.name)}</b>${p.archived?'<span class="tag">Archived</span>':''}<button data-person-edit="${esc(p.id)}">Edit person</button><button data-person-toggle="${esc(p.id)}">${p.archived?'Restore person':'Archive person'}</button><div class="hint">${(p.wageHistory||[]).slice().sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate)||b.revision-a.revision).map(w=>`${esc(w.effectiveDate)} · ${w.currency==='CAD'?'':'Unsupported '+esc(w.currency)+' · '}day ${esc(w.day===''?'unknown':w.day)} · hour ${esc(w.hour===''?'unknown':w.hour)}${w.supersedes?' · replaces prior schedule on this date':''}`).join('<br>')||'No wage history recorded.'}</div><div data-person-box="${esc(p.id)}"></div></div>`).join('')||'<div class="empty">Add people before recording labour or worker payouts.</div>'}</section>`:''}`;
 const manage=document.getElementById('managePeople');manage.disabled=!allowed;manage.onclick=()=>document.getElementById('accountPeople')?.scrollIntoView({behavior:'smooth',block:'start'});
 document.getElementById('legacyHours').onclick=()=>{view='legacyHours';render();window.scrollTo(0,0);};
 app.querySelectorAll('[data-labour-project]').forEach(b=>b.onclick=()=>{openProjectId=b.dataset.labourProject;view='projects';financeTab='labour';render();window.scrollTo(0,0);});
 if(!allowed)return;document.getElementById('peopleRefresh').onclick=renderLabour;
 const change=async op=>{try{await peopleChange(op);renderLabour();}catch(e){document.getElementById('peopleError').textContent=e.message;}};
 const form=document.getElementById('peopleAdd');form.onsubmit=e=>{e.preventDefault();change(personFormOperation(form,'personAdd'));};document.getElementById('peopleCancel').onclick=()=>{form.reset();document.getElementById('peopleError').textContent='';};
 app.querySelectorAll('[data-person-edit]').forEach(b=>b.onclick=()=>{const p=d.people.find(p=>p.id===b.dataset.personEdit),box=app.querySelector(`[data-person-box="${p.id}"]`);box.innerHTML=`<form class="finance-form"><label>Edit person name<input name="name" value="${esc(p.name)}" maxlength="120" required></label>${wageFields()}<div class="finance-toolbar"><button>Save person</button><button type="button" data-person-cancel>Cancel</button></div></form>`;const f=box.querySelector('form'),cancel=()=>{box.innerHTML='';};f.querySelector('[data-person-cancel]').onclick=cancel;f.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();cancel();}};f.onsubmit=e=>{e.preventDefault();change(personFormOperation(f,'personEdit',p.id));};});
 app.querySelectorAll('[data-person-toggle]').forEach(b=>b.onclick=()=>{const person=d.people.find(p=>p.id===b.dataset.personToggle),operation={action:person.archived?'personRestore':'personArchive',personId:person.id};if(person.archived)change(operation);else financeConfirm(b,'Archive this person? New booking dropdowns will hide them. Existing records, rates and pay balances stay visible; you can restore them here.',()=>change(operation));});
 const retry=document.getElementById('peopleRetry');if(retry)retry.onclick=async()=>{try{await peopleTransport.retry(peopleKey(),null);renderLabour();}catch(e){document.getElementById('peopleError').textContent=e.message;}};
 const discard=document.getElementById('peopleDiscard');if(discard)discard.onclick=()=>financeConfirm(discard,'Discard pending People intent? Refresh and inspect current names first; a committed edit is not reversed.',()=>{peopleTransport.discard(peopleKey());renderLabour();});
}
function renderLegacyHours(){const esc=escapeHtml;app.innerHTML=`<div class="h1">Legacy hours</div><button id="backLabour">← Labour</button><div class="finance-warning">Historical time entries are retained as recorded. They are separate from the financial ledger and may overlap labour entries. No person, billing rate, pay rate or day conversion is inferred; these hours are not added to bills. Original time API/MCP tools remain compatible.</div>${[...state.timeEntries].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(e=>`<div class="finance-row"><b>${esc(state.projects.find(p=>p.id===e.projectId)?.name||'Missing project')} · ${esc(e.date||'Unknown date')}</b><div>${esc(e.hours)} hours · Person: ${esc(e.person||e.username||'Unassigned')}</div><div class="hint">${esc(e.note||'')} · Original ID: ${esc(e.id)}</div></div>`).join('')||'<div class="empty">No historical hours.</div>'}`;document.getElementById('backLabour').onclick=()=>{view='labour';render();};}
