const assert=require('node:assert/strict');const L=require('./ledger.js');const Client=require('./finance-client.js');
(async()=>{
 const vm=require('node:vm'),fs=require('node:fs');const ui=vm.createContext({DotyFinanceClient:class{},localStorage:{},escapeHtml:s=>String(s),state:{projects:[{id:'owned',name:'Synthetic project'},{id:'shared',name:'Shared',sharedVirtual:true}]}});vm.runInContext(fs.readFileSync('contacts-ui.js','utf8'),ui);const newForm=vm.runInContext('contactFields(null)',ui);assert(newForm.includes('name="name"'));assert(newForm.includes('Synthetic project'));assert(!newForm.includes('>Shared</label>'));

 const {FinanceAccount,financeAccess,peopleAccess,contactsAccess,callFinanceTool}=await import('./backend/finance-account.mjs');const {localNamespace}=await import('./backend/local-storage.mjs');const ns=localNamespace(FinanceAccount);
 const original={projects:[{id:'owned',name:'Synthetic project',notes:'Original note'},{id:'shared',sharedVirtual:true}],timeEntries:[{id:'h',projectId:'owned',hours:2.5}]};const ctx={username:'owner',role:'admin',env:{ENABLE_FINANCE_REVIEW:'true',FINANCE_ACCOUNTS:ns,DOTY_KV:{get:async k=>k==='data:owner'?JSON.stringify({data:original}):null}}};let n=0;
 const personChange=async(action,extra)=>peopleAccess(ctx,{action,operationId:'wage-person-'+(++n),previousRevision:(await peopleAccess(ctx)).revision,...extra});
 const first=await personChange('personAdd',{name:'Synthetic worker',wageDay:'350.00',wageHour:'45.00',wageCurrency:'CAD',wageEffectiveDate:'2026-09-01'}),id=first.result.personId;
 const finRead=()=>financeAccess(ctx,{project_id:'owned'},false);const change=async(action,extra)=>financeAccess(ctx,{project_id:'owned',mutation:{action,operationId:'wage-finance-'+(++n),previousRevision:(await finRead()).revision,...extra}},true,'browser');
 const phaseId=(await change('phaseAdd',{name:'Main'})).result.phaseIds[0];await change('currencySet',{currency:'CAD'});
 const row=(date,extra={})=>({kind:'labour',phaseId,personId:id,currency:'CAD',date,unit:'days',quantity:'0.5',billRate:'600.00',provenance:{reference:'Synthetic day '+(++n),text:'Worked half day',sourceId:'synthetic-day-'+n},...extra});
 const old=await change('add',{rows:[row('2026-09-15')]});assert.equal(old.ledger.rows[0].payRate,'350.00');assert.equal(old.ledger.rows[0].wageScheduleId,first.ledger.people[0].wageHistory[0].id);const originalRow=JSON.stringify(old.ledger.rows[0]);
 await personChange('personEdit',{personId:id,name:'Renamed synthetic worker',wageDay:'400.00',wageHour:'50.00',wageCurrency:'CAD',wageEffectiveDate:'2026-10-01'});
 await personChange('personEdit',{personId:id,name:'Renamed synthetic worker',wageDay:'450.00',wageHour:'55.00',wageCurrency:'CAD',wageEffectiveDate:'2026-11-01'});
 assert.equal(JSON.stringify((await finRead()).rows[0]),originalRow);
 const current=await change('add',{rows:[row('2026-10-02')]});assert.equal(current.ledger.rows.find(r=>r.id===current.result.rowIds[0]).payRate,'400.00');
 const back=await change('add',{rows:[row('2026-09-02',{unit:'hours',quantity:'2.5',billRate:'80.00'})]});assert.equal(back.ledger.rows.find(r=>r.id===back.result.rowIds[0]).payRate,'45.00');assert.equal(L.lineCost('45.00','2.5'),11250);
 const noHistory=await change('add',{rows:[row('2026-08-01')]});assert.equal(noHistory.ledger.rows.find(r=>r.id===noHistory.result.rowIds[0]).payRate,'');assert.equal(noHistory.ledger.totals.CAD.unknownPay,1);
 await assert.rejects(callFinanceTool('get_person_wage',{person_id:id,work_date:'2026-10-02',currency:'USD',unit:'days'},ctx),/Unknown tool arguments/);assert.equal((await callFinanceTool('get_person_wage',{person_id:id,work_date:'2026-10-02',unit:'hours'},ctx)).value,'50.00');
 const staged=await change('stage',{rows:[row('2026-09-15',{payRate:'350.00'})]});const proposal=staged.ledger.proposals[0];await personChange('personEdit',{personId:id,name:'Renamed synthetic worker',wageDay:'360.00',wageHour:'46.00',wageCurrency:'CAD',wageEffectiveDate:'2026-09-01'});const p=(await peopleAccess(ctx)).people[0];assert.equal(p.wageHistory.length,4);assert(p.wageHistory.at(-1).supersedes);assert.equal(L.wageFor(p,'days','CAD','2026-09-02').value,'360.00');assert.equal(JSON.stringify((await finRead()).rows[0]),originalRow);assert.equal((await finRead()).proposals[0].row.payRate,'350.00');
 await personChange('personArchive',{personId:id});assert.equal((await peopleAccess(ctx)).people[0].archived,true);await assert.rejects(change('add',{rows:[row('2026-09-15',{payRate:'350.00'})]}),/archived/);
 await assert.rejects(change('accept',{proposalId:proposal.id,confirmed:true,phaseId,personId:id}),/archived/);assert.equal((await finRead()).proposals[0].row.payRate,'350.00');
 const accepted=await change('accept',{proposalId:proposal.id,confirmed:true,phaseId,personId:id,historicalPerson:true});assert.equal(accepted.ledger.rows.find(r=>r.id===accepted.result.rowIds[0]).payRate,'350.00');assert.equal(L.workerLabel(accepted.ledger,'id:'+id),'Renamed synthetic worker · Archived');
 const corrected=await callFinanceTool('correct_finance_row',{project_id:'owned',operation_id:'archived-safe-correction',previous_revision:accepted.ledger.revision,row_id:old.ledger.rows[0].id,reason:'Synthetic historical correction',row:row('2026-09-15',{payRate:'350.00',quantity:'0.25'})},ctx);assert.equal(corrected.ledger.rows.find(r=>r.id===corrected.result.rowIds[0]).payRate,'350.00');
 await personChange('personRestore',{personId:id});assert.equal((await peopleAccess(ctx)).people[0].archived,false);assert.equal((await callFinanceTool('get_person_wage',{person_id:id,work_date:'2026-09-02',unit:'days'},ctx)).value,'360.00');
 const zero=await personChange('personEdit',{personId:id,name:'Renamed synthetic worker',wageDay:'0.00',wageHour:'',wageCurrency:'CAD',wageEffectiveDate:'2026-12-01'});assert.equal(L.wageFor(zero.ledger.people[0],'days','CAD','2026-12-01').value,'0.00');assert.equal(L.wageFor(zero.ledger.people[0],'hours','CAD','2026-12-01').value,'');
 const before=JSON.stringify(await peopleAccess(ctx));for(const changes of [{wageDay:'-1',wageHour:'',wageCurrency:'CAD',wageEffectiveDate:'2026-09-01'},{wageDay:'1.001',wageHour:'',wageCurrency:'CAD',wageEffectiveDate:'2026-09-01'},{wageDay:'1.00',wageHour:'',wageCurrency:'CAD',wageEffectiveDate:'2026-02-30'},{wageDay:'1.00',wageHour:''}])await assert.rejects(personChange('personEdit',{personId:id,name:'Renamed synthetic worker',...changes}));assert.equal(JSON.stringify(await peopleAccess(ctx)),before);
 await assert.rejects(peopleAccess({...ctx,role:'user'}),e=>e.status===403);assert.equal((await peopleAccess({...ctx,username:'other',role:'manager'})).people.length,0);
 // Contacts are a distinct namespace; links are exact owned project IDs.
 const contactRead=()=>contactsAccess(ctx);const contactChange=async(action,fields)=>contactsAccess(ctx,{}, {action,operationId:'contact-operation-'+(++n),previousRevision:(await contactRead()).revision,...fields});
 const contact={type:'supplier',name:'Synthetic tile supplier',company:'Example Supplies',contactPerson:'Demo contact',phone:'555-0100',email:'demo@example.invalid',categories:['Tile',' tile ','Stone'],serviceArea:'Demo region',leadTime:'Confirm availability',notes:'Synthetic private note',projectIds:['owned']};
 const created=await callFinanceTool('add_account_contact',{operation_id:'contact-create-first',previous_revision:0,contact},ctx),contactId=created.result.contactId;assert.equal(created.ledger.contacts[0].categories.length,2);assert.equal((await contactsAccess(ctx,{search:'STONE'})).contacts.length,1);assert.equal((await contactsAccess(ctx,{search:'private note'})).contacts.length,1);assert.equal((await callFinanceTool('add_account_contact',{operation_id:'contact-create-first',previous_revision:0,contact},ctx)).replayed,true);
 await assert.rejects(contactChange('contactAdd',{contact:{...contact,projectIds:['other-owner-project']}}),/owned projects/);await assert.rejects(contactChange('contactAdd',{contact:{...contact,name:'Other',projectIds:['shared']}}),/owned projects/);await assert.rejects(contactChange('contactAdd',{contact:{...contact,name:'Invalid mail',email:'bad-email'}}),/email/);await assert.rejects(contactChange('contactAdd',{contact:{...contact,bankAccount:'forbidden'}}),/Invalid contact fields/);await assert.rejects(contactChange('contactAdd',{contact}),/already exists/);
 const edited=await contactChange('contactEdit',{contactId,contact:{leadTime:'Two weeks'}});assert.equal(edited.ledger.contacts[0].id,contactId);assert.equal(edited.ledger.contacts[0].leadTime,'Two weeks');await contactChange('contactArchive',{contactId});assert.equal((await contactsAccess(ctx,{include_archived:false})).contacts.length,0);assert.equal((await contactRead()).contacts[0].archived,true);await contactChange('contactRestore',{contactId});assert.equal((await contactRead()).contacts[0].archived,false);
 const revision=(await contactRead()).revision;const races=await Promise.allSettled(['Synthetic A','Synthetic B'].map((name,i)=>contactsAccess(ctx,{}, {action:'contactAdd',operationId:'contact-race-'+i,previousRevision:revision,contact:{type:'subtrade',name,categories:[],projectIds:[]}})));assert.equal(races.filter(x=>x.status==='fulfilled').length,1);assert.equal(races.find(x=>x.status==='rejected').reason.status,409);
 const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};let lost=true;const transport=new Client({storage,newId:()=> 'contact-lost-response',request:async(_,mutation)=>{const result=await contactsAccess(ctx,{},mutation);if(mutation&&lost){lost=false;throw Error('Lost response');}return result;}});await transport.load('contacts',null);await assert.rejects(transport.mutate('contacts',null,(await contactRead()).revision,{action:'contactEdit',contactId,contact:{phone:'555-0101'}}),/Lost response/);assert.equal((await transport.retry('contacts',null)).replayed,true);assert.equal((await contactRead()).contacts.filter(c=>c.id===contactId).length,1);
 await assert.rejects(contactsAccess({...ctx,role:'user'}),e=>e.status===403);assert.equal((await contactsAccess({...ctx,username:'other',role:'manager'})).contacts.length,0);assert(!JSON.stringify(await contactRead()).includes('wageHistory'));assert.equal((await peopleAccess(ctx)).people.length,1);assert.equal(original.projects[0].notes,'Original note');assert.equal(original.timeEntries[0].hours,2.5);
 console.log('PASS: effective day/hour wage history, future/backdated/missing/zero rates, immutable entry/proposal snapshots, same-date corrections, archive/new booking refusal/historical acceptance/restore, private wage lookup, separate contacts CRUD/search/archive/privacy, owned links, validation, CAS and lost-response replay.');
})().catch(e=>{console.error(e);process.exitCode=1});
