import {ownerBackupAccess} from './owner-account.mjs';
import '../backup.js';
const B=globalThis.DotyBackup;
const fail=(message,status=400)=>{const e=Error(message);e.status=status;throw e;};
async function call(ns,name,pathname,body=null){const res=await ns.get(ns.idFromName(name)).fetch(new Request('https://finance.internal/'+pathname,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{}));const value=await res.json();if(!res.ok)fail(value.error,res.status);return value;}
export async function registerBackupProject(ctx,projectId){if(!ctx.env.FINANCE_ACCOUNTS)return;return call(ctx.env.FINANCE_ACCOUNTS,JSON.stringify({kind:'backup-index',owner:ctx.username}),'backup-index',{projectId});}
export async function backupStoreRequest(storage,request){const url=new URL(request.url);if(url.pathname==='/backup-snapshot'&&request.method==='GET')return storage.transaction(async tx=>[...(await tx.list())]);if(url.pathname==='/backup-index'){return storage.transaction(async tx=>{const ids=await tx.get('backup-project-ids')||[];if(request.method==='POST'){const {projectId}=await request.json();if(typeof projectId!=='string'||!projectId||projectId.length>100)fail('Invalid project ID.');if(!ids.includes(projectId)){ids.push(projectId);await tx.put('backup-project-ids',ids);}}else if(request.method!=='GET')fail('Method not allowed',405);return {projectIds:ids};});}fail('Not found',404);}
export async function accountBackupAccess(ctx){if(ctx.env.OWNER_ACCOUNT_MODE==='fresh-v8')return ownerBackupAccess(ctx);if(ctx.env.BACKUP_INDEX_COMPLETE!=='true')fail('Complete remote inventory must be certified for a fresh V8 namespace before export. No partial backup generated.',503);if(ctx.env.ENABLE_FINANCE_REVIEW!=='true'||!ctx.env.FINANCE_ACCOUNTS)fail('Complete account backup requires the reviewed transactional backend. No partial backup generated.',503);if(!['admin','manager'].includes(ctx.role))fail('Private full backup requires your own manager account.',403);
 const ns=ctx.env.FINANCE_ACCOUNTS,load=async()=>{const raw=await ctx.env.DOTY_KV.get('data:'+ctx.username);if(!raw)fail('Owned tracker state unavailable.',404);const record=JSON.parse(raw);if(!record?.data?.projects)fail('Invalid tracker state.');const index=await call(ns,JSON.stringify({kind:'backup-index',owner:ctx.username}),'backup-index');const ids=[...new Set([...record.data.projects.filter(p=>!p.sharedVirtual).map(p=>p.id),...index.projectIds])].sort();const stores=[];for(const kind of ['people','contacts'])stores.push({kind,entries:await call(ns,JSON.stringify({kind,owner:ctx.username}),'backup-snapshot')});for(const projectId of ids)stores.push({kind:'finance',projectId,entries:await call(ns,JSON.stringify([ctx.username,projectId]),'backup-snapshot')});return {tracker:B.tracker(record.data),privateStores:stores};};
 // Never download a mixture of concurrent versions or silently skip a failed store.
 for(let attempt=0;attempt<2;attempt++){const a=await load(),b=await load();if(await B.hash(a)===await B.hash(b))return B.create(a.tracker,a.privateStores,ctx.username);}fail('Account changed during complete backup discovery. Retry after edits settle.',409);
}
