/* Isolated review adapter, not a production KV replacement. All HTTP API operations
   run through one gate. A durable journal rolls back an interrupted multi-file
   restore before any stores are opened on restart. */
import fs from 'node:fs/promises';
import path from 'node:path';
import '../ledger.js';
import '../backup.js';
const B=globalThis.DotyBackup;
const fail=(message,status=400)=>{const e=Error(message);e.status=status;throw e;};
const write=async(file,data)=>{await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file+'.tmp',JSON.stringify(data));await fs.rename(file+'.tmp',file);};
export async function recoverRestore(root){const file=path.join(root,'.preview','restore-journal.json');let j;try{j=JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if(e.code==='ENOENT')return;throw e;}if(j.status==='applying'){for(const record of j.before){if(record.entries===null)await fs.rm(record.file,{force:true});else await write(record.file,record.entries);}j.status='rolledBack';j.error='Interrupted restore rolled back before startup.';await write(file,j);}}
export class LocalBackupService{
 constructor({root,namespace,owner='demo-owner',failAfter=null}){Object.assign(this,{root,namespace,owner,failAfter});this.file=path.join(root,'.preview','restore-journal.json');}
 name(s){return s.kind==='finance'?JSON.stringify([this.owner,s.projectId]):JSON.stringify({kind:s.kind,owner:this.owner});}
 fileFor(name){return path.join(this.root,'.preview',Buffer.from(name).toString('base64url')+'.json');}
 async discover(projects){const names=new Set(projects.map(p=>JSON.stringify([this.owner,p.id])));for(const kind of ['people','contacts'])names.add(JSON.stringify({kind,owner:this.owner}));let files=[];try{files=await fs.readdir(path.join(this.root,'.preview'));}catch(e){if(e.code!=='ENOENT')throw e;}for(const file of files.filter(f=>f.endsWith('.json'))){let parsed;try{parsed=JSON.parse(Buffer.from(file.slice(0,-5),'base64url').toString());}catch{continue;}if(Array.isArray(parsed)&&parsed.length===2&&parsed[0]===this.owner)names.add(JSON.stringify(parsed));if(parsed&&!Array.isArray(parsed)&&['people','contacts'].includes(parsed.kind)&&parsed.owner===this.owner)names.add(JSON.stringify(parsed));}for(const name of this.namespace.instances.keys()){const p=JSON.parse(name);if(Array.isArray(p)&&p[0]===this.owner)names.add(name);}return [...names].sort();}
 async stores(projects){const stores=[];for(const name of await this.discover(projects)){const storage=this.namespace.get(name).storage;await storage.ready;await storage.queue.catch(()=>{});const p=JSON.parse(name),s=Array.isArray(p)?{kind:'finance',projectId:p[1]}:{kind:p.kind};stores.push({...s,entries:[...storage.map]});}return stores;}
 async export(tracker){const stores=await this.stores(tracker.projects.filter(p=>!p.sharedVirtual));return B.create(tracker,stores,this.owner);}
 async currentDigest(tracker){return B.hash((await this.export(tracker)).payload);}
 async readJournal(){try{return JSON.parse(await fs.readFile(this.file,'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
 async prepare(bundle,currentTracker,expected){const validated=await B.validate(bundle);if(!validated.legacy&&bundle.manifest.owner!==this.owner)fail('Backup belongs to another owner. Cross-owner restore is not supported.',403);if(await this.currentDigest(currentTracker)!==expected)fail('Account changed after preview. Export/preview again.',409);const prior=await this.readJournal();if(prior?.status==='applying')fail('A recovery is in progress.',409);const token=crypto.randomUUID(),current=await this.export(currentTracker);const payload=validated.legacy?{tracker:validated.tracker,privateStores:current.payload.privateStores}:validated.bundle.payload;const journal={token,status:'prepared',expected,currentTracker:B.tracker(currentTracker),payload,legacy:validated.legacy,createdAt:new Date().toISOString()};await write(this.file,journal);return {token,status:journal.status,warnings:validated.warnings};}
 async apply(token,currentTracker){const j=await this.readJournal();if(!j||j.token!==token)fail('Unknown restore proposal.',404);if(j.status==='committed')return {status:j.status,tracker:j.payload.tracker,replayed:true};if(j.status!=='prepared')fail('Restore is not prepared. Preview again.',409);if(await this.currentDigest(currentTracker)!==j.expected)fail('Account changed since preview. Nothing restored.',409);
 const existing=await this.stores(currentTracker.projects),target=new Map(j.payload.privateStores.map(s=>[this.name(s),s.entries]));for(const s of existing)if(!target.has(this.name(s)))target.set(this.name(s),[]);const changes=[...target].map(([name,entries])=>{const identity=JSON.parse(name),kind=Array.isArray(identity)?'finance':identity.kind,key=kind==='finance'?'revision':(kind==='contacts'?'contact':kind)+'-revision',before=existing.find(s=>this.name(s)===name),priorRevision=new Map(before?.entries||[]).get(key)||0,next=new Map(structuredClone(entries)),revision=Math.max(priorRevision,next.get(key)||0)+1;next.set(key,revision);const prefix=kind==='finance'?'audit:':(kind==='contacts'?'contact':kind)+'-audit:';next.set(prefix+String(revision).padStart(12,'0'),{id:j.token,revision,action:'backupRestore',actor:this.owner,at:new Date().toISOString(),note:'Explicit reviewed whole-account replacement; source snapshots/history preserved.'});return {name,file:this.fileFor(name),entries:[...next]};});const trackerFile=path.join(this.root,'.preview','restored-tracker.json');let previousTracker=null;try{previousTracker=JSON.parse(await fs.readFile(trackerFile,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
 j.before=[];for(const c of changes){let previous=null;try{previous=JSON.parse(await fs.readFile(c.file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}j.before.push({file:c.file,entries:previous});}j.before.push({file:trackerFile,entries:previousTracker});j.status='applying';await write(this.file,j);
 try{let count=0;for(const c of changes){await write(c.file,c.entries);if(this.failAfter!==null&&++count===this.failAfter)throw Error('Injected restore write failure');}await write(trackerFile,j.payload.tracker);for(const c of changes){const storage=this.namespace.get(c.name).storage;storage.map=new Map(structuredClone(c.entries));}j.status='committed';await write(this.file,j);return {status:j.status,tracker:j.payload.tracker};}catch(e){for(const c of j.before){if(c.entries===null)await fs.rm(c.file,{force:true});else await write(c.file,c.entries);}for(const c of changes){const prior=j.before.find(p=>p.file===c.file).entries;this.namespace.get(c.name).storage.map=new Map(prior||[]);}j.status='rolledBack';j.error=e.message;await write(this.file,j);fail('Restore failed and rolled back. Original account retained: '+e.message,500);}
 }
 async status(token){const j=await this.readJournal();if(!j||j.token!==token)fail('Unknown restore proposal.',404);return {status:j.status,...(j.status==='committed'?{tracker:j.payload.tracker}:{}),error:j.error||null};}
}
