import '../ledger.js';
const L=globalThis.DotyLedger;
const fail=(message,status=400)=>{const e=Error(message);e.status=status;throw e;};
const exact=(x,fields)=>{if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).some(k=>!fields.includes(k)))fail('Invalid contact fields.');};
const FIELDS=['type','name','company','contactPerson','phone','email','categories','serviceArea','leadTime','notes','projectIds'];
function contactRecord(input,prior,allowed){
 exact(input,FIELDS);const record={...(prior||{})};
 for(const key of FIELDS.filter(k=>!['categories','projectIds'].includes(k))){if(input[key]!==undefined){const max=key==='notes'?10000:key==='email'?254:key==='phone'?80:200;if(typeof input[key]!=='string'||input[key].length>max)fail('Invalid '+key+'.');record[key]=key==='notes'?input[key]:input[key].normalize('NFC').trim().replace(/\s+/g,' ');}}
 if(!['supplier','subtrade'].includes(record.type)||!(record.name||record.company))fail('Choose supplier/subtrade and enter a name or company.');
 if(record.email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(record.email))fail('Invalid email address.');
 if(input.categories!==undefined){if(!Array.isArray(input.categories)||input.categories.length>30||input.categories.some(v=>typeof v!=='string'||!v.trim()||v.length>120))fail('Categories require up to 30 non-empty names.');record.categories=[...new Map(input.categories.map(v=>[L.phaseKey(v),L.phaseName(v)])).values()];}
 if(input.projectIds!==undefined){if(!Array.isArray(input.projectIds)||input.projectIds.length>100||input.projectIds.some(v=>typeof v!=='string'||!v||v.length>100||!allowed.includes(v)&&!prior?.projectIds?.includes(v)))fail('Contact links must use existing owned projects.');record.projectIds=[...new Set(input.projectIds)];}
 record.categories=record.categories||[];record.projectIds=record.projectIds||[];return record;
}
const key=c=>JSON.stringify([c.type,(c.name||'').toLocaleLowerCase(),(c.company||'').toLocaleLowerCase(),(c.contactPerson||'').toLocaleLowerCase(),(c.email||'').toLocaleLowerCase()]);
export async function contactsRequest(storage,request){
 const read=async tx=>{const all=await tx.list();return {version:1,revision:all.get('contact-revision')||0,contacts:[...all].filter(([k])=>k.startsWith('contact:')).map(([,v])=>v).sort((a,b)=>(a.name||a.company).localeCompare(b.name||b.company)),rows:[],proposals:[],audit:[...all].filter(([k])=>k.startsWith('contact-audit:')).map(([,v])=>v)};};
 if(request.method==='GET')return storage.transaction(read);
 const raw=await request.text();if(raw.length>1000000)fail('Contact request too large.',413);const body=JSON.parse(raw);exact(body,['actor','mutation','allowedProjects']);const m=body.mutation,editing=['contactAdd','contactEdit'].includes(m?.action);exact(m,['action','contactId','operationId','previousRevision',...(editing?['contact']:[])]);
 if(!['contactAdd','contactEdit','contactArchive','contactRestore'].includes(m.action)||!Number.isSafeInteger(m.previousRevision)||m.previousRevision<0||!/^[A-Za-z0-9_-]{8,128}$/.test(m.operationId||''))fail('Invalid contact operation.');if(m.action==='contactAdd'&&m.contactId!==undefined)fail('Contact ID is not allowed when adding.');
 const fingerprint=JSON.stringify([m.action,m.contactId||null,editing?Object.fromEntries(Object.entries(m.contact||{}).sort(([a],[b])=>a.localeCompare(b))):null,m.previousRevision,body.actor]);
 return storage.transaction(async tx=>{const receipt=await tx.get('contact-operation:'+m.operationId);if(receipt){if(receipt.fingerprint!==fingerprint)fail('Contact operation ID reused with a different payload.',409);return {result:receipt.result,ledger:await read(tx),replayed:true};}const d=await read(tx);if(d.revision!==m.previousRevision)fail('Contact revision conflict. Refresh and review.',409);const prior=m.action==='contactAdd'?null:d.contacts.find(c=>c.id===m.contactId);if(m.action!=='contactAdd'&&!prior)fail('Contact not found.',404);if(m.action==='contactAdd'&&d.contacts.length>=1000)fail('Maximum 1000 contacts per account.');const record=editing?contactRecord(m.contact,prior,body.allowedProjects||[]):{...prior,archived:m.action==='contactArchive'};if(editing&&d.contacts.some(c=>c.id!==prior?.id&&key(c)===key(record)))fail('This contact already exists. Edit or restore the existing record.');const at=new Date().toISOString();record.id=prior?.id||crypto.randomUUID();record.editedAt=at;record.editedBy=body.actor;await tx.put('contact:'+record.id,record);const revision=d.revision+1;await tx.put('contact-revision',revision);const result={revision,contactId:record.id};await tx.put('contact-audit:'+revision,{id:m.operationId,revision,action:m.action,contactId:record.id,prior:prior||null,record,actor:body.actor,at});await tx.put('contact-operation:'+m.operationId,{fingerprint,result});return {result,ledger:await read(tx)};});
}
export async function contactsAccess(ctx,args={},mutation=null){
 if(ctx.env.ENABLE_FINANCE_REVIEW!=='true')fail('Finance feature unavailable.',503);if(!['admin','manager'].includes(ctx.role))fail('Private contacts require owner admin/manager role.',403);exact(args,['search','include_archived']);if(args.search!==undefined&&(typeof args.search!=='string'||args.search.length>200))fail('Search requires at most 200 characters.');if(args.include_archived!==undefined&&typeof args.include_archived!=='boolean')fail('include_archived must be boolean.');const ns=ctx.env.FINANCE_ACCOUNTS;if(!ns?.get)fail('Transactional finance binding required.',503);const raw=await ctx.env.DOTY_KV.get('data:'+ctx.username),projects=raw?JSON.parse(raw)?.data?.projects||[]:[];const stub=ns.get(ns.idFromName(JSON.stringify({kind:'contacts',owner:ctx.username}))),res=await stub.fetch(new Request('https://finance.internal/contacts',mutation?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actor:ctx.username,mutation,allowedProjects:projects.filter(p=>!p.sharedVirtual).map(p=>p.id)})}:{}));const value=await res.json();if(!res.ok)fail(value.error,res.status);if(!mutation){const q=(args.search||'').trim().toLocaleLowerCase();value.contacts=value.contacts.filter(c=>(args.include_archived!==false||!c.archived)&&(!q||[c.name,c.company,c.contactPerson,c.phone,c.email,c.serviceArea,c.leadTime,c.notes,...c.categories].filter(Boolean).join(' ').toLocaleLowerCase().includes(q)));}return value;
}
const contactSchema={type:'object',additionalProperties:false,properties:Object.fromEntries(FIELDS.map(k=>[k,k==='categories'||k==='projectIds'?{type:'array',items:{type:'string'}}:k==='type'?{type:'string',enum:['supplier','subtrade']}:{type:'string'}]))};
export const CONTACT_TOOLS=['list_account_contacts','add_account_contact','edit_account_contact','archive_account_contact','restore_account_contact'].map(name=>{const list=name==='list_account_contacts',edit=['add_account_contact','edit_account_contact'].includes(name),id=name!=='add_account_contact'&&!list;return {name,description:'Owner-private internal supplier/subtrade directory. No outreach, login, bank data, automatic import or external service. Links require owned projects. Archive preserves history. Read revision and reuse operation ID.',inputSchema:{type:'object',additionalProperties:false,properties:list?{search:{type:'string'},include_archived:{type:'boolean'}}:{operation_id:{type:'string'},previous_revision:{type:'integer'},...(edit?{contact:contactSchema}:{}),...(id?{contact_id:{type:'string'}}:{})},required:list?[]:['operation_id','previous_revision',...(edit?['contact']:[]),...(id?['contact_id']:[])]}};});
export function callContactTool(name,args,ctx){if(name==='list_account_contacts')return contactsAccess(ctx,args);return contactsAccess(ctx,{}, {action:{add_account_contact:'contactAdd',edit_account_contact:'contactEdit',archive_account_contact:'contactArchive',restore_account_contact:'contactRestore'}[name],operationId:args.operation_id,previousRevision:args.previous_revision,...(args.contact!==undefined?{contact:args.contact}:{}),...(args.contact_id?{contactId:args.contact_id}:{})});}
