/* Fresh V8 mode: one Durable Object per owner, using the existing binding/class.
   All logical store and tracker writes share its transaction boundary. No KV or
   other DO calls occur inside these transactions. Legacy split stores untouched. */
import '../ledger.js';
import '../backup.js';
const B=globalThis.DotyBackup;
const fail=(message,status=400)=>{const e=Error(message);e.status=status;throw e;};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const empty=()=>({projects:[],timeEntries:[],settings:{},view:'calendar',calendarMode:'day',initialized:true});
const prefix=id=>'owned-store:'+encodeURIComponent(id)+':';
const idFor=name=>{const n=JSON.parse(name);if(Array.isArray(n)&&n.length===2)return {owner:n[0],id:'finance:'+n[1]};if(['people','contacts','backup-index'].includes(n?.kind))return {owner:n.owner,id:n.kind};fail('Invalid owned store.');};
// Smaller than Cloudflare's per-value limit even for non-ASCII text. No large
// tracker/proposal/recovery bundle is stored as a single Durable Object value.
async function putJSON(tx,key,value){const text=JSON.stringify(value),old=await tx.get(key+':count')||0,chunks=Math.ceil(text.length/16000);for(let i=0;i<chunks;i++)await tx.put(key+':'+i,text.slice(i*16000,(i+1)*16000));for(let i=chunks;i<old;i++)await tx.delete(key+':'+i);await tx.put(key+':count',chunks);}
async function getJSON(tx,key){const n=await tx.get(key+':count');if(n===undefined)return null;let text='';for(let i=0;i<n;i++){const part=await tx.get(key+':'+i);if(typeof part!=='string')fail('Incomplete account record.',500);text+=part;}return JSON.parse(text);}
async function retire(tx,token){if(!token)return;const key='restore:'+token,j=await getJSON(tx,key);if(!j)return;const n=await tx.get(key+':count')||0;for(let i=0;i<n;i++)await tx.delete(key+':'+i);await tx.delete(key+':count');await tx.put(key+':retired',{fingerprint:j.fingerprint,status:j.status,generation:j.generation});}
async function proposal(tx,token){const j=await getJSON(tx,'restore:'+token);if(!j&&await tx.get('restore:'+token+':retired'))fail('Restore receipt retired; export and preview again. This token cannot be reused.',410);return j;}
async function listAll(tx,p){const all=new Map();let startAfter;for(;;){const page=await tx.list({prefix:p,limit:1000,...(startAfter?{startAfter}:{})});const rows=[...page].filter(([k])=>k.startsWith(p)&&(!startAfter||k>startAfter)).sort(([a],[b])=>a<b?-1:a>b?1:0).slice(0,1000);for(const [k,v]of rows)all.set(k,v);if(rows.length<1000)break;startAfter=rows.at(-1)[0];}return all;}
function partition(tx,id){const p=prefix(id);return {get:k=>tx.get(p+k),put:async(k,v)=>{if(new TextEncoder().encode(JSON.stringify(v)).length>100000)fail('Stored record exceeds the safe per-value limit.',413);await tx.put(p+k,v);},delete:k=>tx.delete(p+k),list:async()=>new Map([...(await listAll(tx,p))].map(([k,v])=>[k.slice(p.length),v])),transaction:fn=>fn(partition(tx,id))};}
// Restore files never carry grants. Preserve the current server-owned item grants
// for matching project/kind/item IDs; restoring cannot grant new recipients.
function currentShares(tracker){return (tracker?.projects||[]).flatMap(p=>['schedule','todos','toBuy'].flatMap(kind=>(p[kind]||[]).filter(i=>Array.isArray(i.sharedWith)).map(i=>({project:p.id,kind,item:i.id,sharedWith:i.sharedWith}))));}
function preserveShares(tracker,current){const grants=currentShares(current);for(const p of tracker.projects)for(const kind of ['schedule','todos','toBuy'])for(const item of p[kind]||[]){const grant=grants.find(g=>g.project===p.id&&g.kind===kind&&g.item===item.id);if(grant)item.sharedWith=structuredClone(grant.sharedWith);}return tracker;}
async function snapshot(tx,owner){const rec=await getJSON(tx,'tracker')||{data:empty(),updatedAt:null};const tracker=B.tracker(rec.data),ids=new Set(await getJSON(tx,'inventory')||[]);for(const p of tracker.projects)ids.add('finance:'+p.id);ids.add('people');ids.add('contacts');const stores=[];for(const id of [...ids].sort()){stores.push({...(id.startsWith('finance:')?{kind:'finance',projectId:id.slice(8)}:{kind:id}),entries:[...(await partition(tx,id).list())]});}return B.create(tracker,stores,owner);}
export async function ownerAccountRequest(storage,request,env){const url=new URL(request.url),body=request.method==='POST'?await request.json():{},owner=body.owner||url.searchParams.get('owner');if(typeof owner!=='string'||!/^[a-z0-9-]{3,20}$/.test(owner))fail('Invalid account owner.');
 return storage.transaction(async tx=>{const bound=await tx.get('owner');if(bound&&bound!==owner)fail('Owner mismatch.',403);if(!bound)await tx.put('owner',owner);const generation=await tx.get('generation')||0;
 if(url.pathname==='/owner-meta')return {generation,active:await tx.get('active')===true,pending:await tx.get('migration-pending')===true};
 if(url.pathname==='/owner-tracker'){
  const record=await getJSON(tx,'tracker')||{data:empty(),updatedAt:null};if(request.method==='GET')return {record,generation};if(body.expectedGeneration!==generation||body.previousUpdatedAt!==record.updatedAt)fail('Account changed; reload before writing.',409);if(body.action==='delete')fail('Account deletion needs a separate reviewed lifecycle.',409);if(!body.record?.data)fail('Missing tracker record.');B.validateTracker(B.tracker(body.record.data));const updatedAt=new Date(Math.max(Date.now(),Date.parse(record.updatedAt||'')+1||0)).toISOString();await putJSON(tx,'tracker',{data:body.record.data,updatedAt});return {updatedAt,generation};
 }
 if(url.pathname==='/owner-store'){
  if(body.expectedGeneration!==generation)fail('Account was restored during this request; reload before writing.',409);const identity=idFor(body.name);if(identity.owner!==owner)fail('Owner mismatch.',403);if(identity.id==='backup-index')return {projectIds:(await getJSON(tx,'inventory')||[]).filter(i=>i.startsWith('finance:')).map(i=>i.slice(8))};
  const inventory=await getJSON(tx,'inventory')||[];if(!inventory.includes(identity.id)){inventory.push(identity.id);await putJSON(tx,'inventory',inventory);}const {FinanceAccount}=await import('./finance-account.mjs');const handler=new FinanceAccount({storage:partition(tx,identity.id)},env);const response=await handler.fetch(new Request('https://finance.internal'+body.path,{method:body.method,headers:body.headers,...(body.method==='POST'?{body:body.text}:{})}));const result=await response.json();if(!response.ok)fail(result.error,response.status);return result;
 }
 if(url.pathname!=='/owner-backup')fail('Not found',404);const action=body.action||'export';if(env.OWNER_ACTIVATE_ON_RESTORE==='true'&&await tx.get('active')!==true&&body.initialRecord?.data){B.validateTracker(B.tracker(body.initialRecord.data));await putJSON(tx,'tracker',body.initialRecord);}
 if(action==='export')return snapshot(tx,owner);
 if(action==='cancel'){const j=await proposal(tx,body.token);if(!j)fail('Unknown restore proposal.',404);if(j.status!=='prepared')fail('Only a prepared restore can be cancelled.',409);j.status='cancelled';await putJSON(tx,'restore:'+j.token,j);if(await tx.get('prepared-token')===j.token){await tx.delete('prepared-token');await tx.put('migration-pending',false);}return {status:'cancelled'};}
 if(action==='status'||action==='recovery'){const j=await proposal(tx,body.token);if(!j)fail('Unknown restore proposal.',404);if(action==='recovery')return j.before;return {status:j.status,token:j.token,recoveryAvailable:true,...(j.status==='committed'?{tracker:j.payload.tracker,updatedAt:j.updatedAt,generation:j.generation}:{})};}
 if(action==='prepare'){
  const raw=JSON.stringify(body.bundle);if(new TextEncoder().encode(raw).length>20000000)fail('Backup exceeds 20 MB review limit.',413);const checked=await B.validate(body.bundle);if(!checked.legacy&&checked.bundle.manifest.owner!==owner)fail('Cross-owner restore is not supported.',403);const token=body.operationId;if(typeof token!=='string'||!/^[A-Za-z0-9_-]{8,128}$/.test(token))fail('Stable restore operationId required.');const fingerprint=await B.hash({bundle:body.bundle,expected:body.expected}),prior=await proposal(tx,token);if(prior){if(prior.fingerprint!==fingerprint)fail('Restore operation ID reused with different input.',409);return {token,status:prior.status,warnings:checked.warnings,replayed:true};}const before=await snapshot(tx,owner);if(await B.hash(before.payload)!==body.expected)fail('Account changed after preview. Nothing restored.',409);const payload=checked.legacy?{tracker:checked.tracker,privateStores:before.payload.privateStores}:checked.bundle.payload;const currentRecord=await getJSON(tx,'tracker');const sharesHash=await B.hash(currentShares(currentRecord?.data));preserveShares(payload.tracker,currentRecord?.data);
  for(const s of payload.privateStores)for(const [k,v]of s.entries)if(new TextEncoder().encode(k).length>1000||new TextEncoder().encode(JSON.stringify(v)).length>100000)fail('Backup record exceeds the safe per-value limit.',413);
  await retire(tx,await tx.get('prepared-token'));await tx.put('prepared-token',token);if(env.OWNER_ACTIVATE_ON_RESTORE==='true'&&await tx.get('active')!==true)await tx.put('migration-pending',true);await putJSON(tx,'restore:'+token,{token,status:'prepared',generation,expected:body.expected,fingerprint,payload,before,sharesHash});return {token,status:'prepared',warnings:checked.warnings};
 }
 if(action==='apply'){
  const j=await proposal(tx,body.token);if(!j)fail('Unknown restore proposal.',404);if(j.status==='committed')return {status:j.status,tracker:j.payload.tracker,updatedAt:j.updatedAt,generation:j.generation,replayed:true};if(j.status!=='prepared')fail('Restore is not prepared.',409);if(j.generation!==generation||await B.hash((await snapshot(tx,owner)).payload)!==j.expected)fail('Account changed since preview. Nothing restored.',409);if(j.sharesHash!==await B.hash(currentShares((await getJSON(tx,'tracker'))?.data)))fail('Sharing changed since preview. Nothing restored.',409);
  const oldInventory=await getJSON(tx,'inventory')||[],incoming=j.payload.privateStores.map(B.storeId),allIds=new Set([...oldInventory,...incoming]);for(const id of allIds){const store=partition(tx,id),old=await store.list(),target=new Map(j.payload.privateStores.find(s=>B.storeId(s)===id)?.entries||[]);const kind=id.startsWith('finance:')?'finance':id,key=kind==='finance'?'revision':(kind==='contacts'?'contact':kind)+'-revision',revision=Math.max(old.get(key)||0,target.get(key)||0)+1;for(const [k]of old)await store.delete(k);for(const [k,v]of target)await store.put(k,v);await store.put(key,revision);await store.put((kind==='finance'?'audit:':(kind==='contacts'?'contact':kind)+'-audit:')+String(revision).padStart(12,'0'),{id:j.token,revision,action:'backupRestore',actor:owner,at:new Date().toISOString(),note:'Reviewed complete replacement; original snapshots retained.'});}
  // Tracker, inventory, fencing generation and durable success receipt commit
  // with every private record. Crash = all previous or all restored, never mix.
  const previous=await getJSON(tx,'tracker');j.updatedAt=new Date(Math.max(Date.now(),Date.parse(previous?.updatedAt||'')+1||0)).toISOString();j.generation=generation+1;j.status='committed';await putJSON(tx,'tracker',{data:j.payload.tracker,updatedAt:j.updatedAt});await putJSON(tx,'inventory',[...allIds].sort());await tx.put('generation',j.generation);if(env.OWNER_ACTIVATE_ON_RESTORE==='true'){await tx.put('active',true);await tx.put('migration-pending',false);}await retire(tx,await tx.get('committed-token'));await tx.put('committed-token',j.token);await tx.delete('prepared-token');await putJSON(tx,'restore:'+j.token,j);return {status:'committed',tracker:j.payload.tracker,updatedAt:j.updatedAt,generation:j.generation};
 }
 fail('Unknown backup action.');
 });
}
async function invoke(ns,owner,path,body=null){const stub=ns.get(ns.idFromName(JSON.stringify({kind:'owner-v8',owner})));const response=await stub.fetch(new Request('https://finance.internal'+path+(body?'':'?owner='+encodeURIComponent(owner)),body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,owner})}:{}));const value=await response.json();if(!response.ok)fail(value.error,response.status);return value;}
// Per-request adapter: account restores fence even requests that obtained project
// permissions/wages before the restore. Credentials/users/MCP tokens stay in KV.
export function ownerEnvironment(env){if(env.OWNER_ACCOUNT_MODE!=='fresh-v8')return env;const ns=env.FINANCE_ACCOUNTS;if(!ns)fail('Owner coordinator binding required.',503);const metas=new Map(),reads=new Map();const meta=async owner=>{if(!metas.has(owner))metas.set(owner,invoke(ns,owner,'/owner-meta'));return metas.get(owner);};const useOwner=async owner=>env.OWNER_ACTIVATE_ON_RESTORE!=='true'||(await meta(owner)).active;const wrapped={...env,OWNER_RAW_NAMESPACE:ns,OWNER_RAW_KV:env.DOTY_KV};wrapped.OWNER_WRITE_AT=owner=>reads.get(owner);wrapped.DOTY_KV={get:async(key,...args)=>{if(!key.startsWith('data:'))return env.DOTY_KV.get(key,...args);const owner=key.slice(5);if(!await useOwner(owner))return env.DOTY_KV.get(key,...args);const result=await invoke(ns,owner,'/owner-tracker');if(!metas.has(owner))metas.set(owner,Promise.resolve({generation:result.generation,active:true}));reads.set(owner,result.record.updatedAt);return JSON.stringify(result.record);},put:async(key,value,...args)=>{if(!key.startsWith('data:'))return env.DOTY_KV.put(key,value,...args);const owner=key.slice(5);if(!await useOwner(owner)){const current=await invoke(ns,owner,'/owner-meta');if(current.active||current.pending)fail('Account migration is in progress; reload before editing.',409);return env.DOTY_KV.put(key,value,...args);}if(!reads.has(owner))await wrapped.DOTY_KV.get(key);const result=await invoke(ns,owner,'/owner-tracker',{record:JSON.parse(value),previousUpdatedAt:reads.get(owner),expectedGeneration:(await meta(owner)).generation});reads.set(owner,result.updatedAt);},delete:async(key,...args)=>{if(key.startsWith('data:'))fail('V8 account deletion requires reviewed lifecycle.',409);return env.DOTY_KV.delete(key,...args);},list:(...args)=>env.DOTY_KV.list(...args)};wrapped.FINANCE_ACCOUNTS={idFromName:name=>name,get:name=>({fetch:async request=>{const {owner}=idFor(name);if(!await useOwner(owner))fail('Private account migration is not activated; existing tracker data remains in KV.',503);return json(await invoke(ns,owner,'/owner-store',{name,path:new URL(request.url).pathname,method:request.method,headers:Object.fromEntries(request.headers),text:request.method==='POST'?await request.text():null,expectedGeneration:(await meta(owner)).generation}));}})};return wrapped;}

export async function ownerBackupAccess(ctx,body={action:'export'}){if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!['action','bundle','expected','operationId','token','tracker'].includes(k)))fail('Invalid backup request.');if(['apply','status','recovery','cancel'].includes(body.action)&&(typeof body.token!=='string'||!/^[A-Za-z0-9_-]{8,128}$/.test(body.token)))fail('Invalid restore token.');if(!['admin','manager'].includes(ctx.role))fail('Private full backup requires your own manager account.',403);if(ctx.env.OWNER_ACCOUNT_MODE!=='fresh-v8')fail('Complete production restore requires fresh V8 owner storage.',503);const scoped={...body};if(ctx.env.OWNER_ACTIVATE_ON_RESTORE==='true'){const raw=await (ctx.env.OWNER_RAW_KV||ctx.env.DOTY_KV).get('data:'+ctx.username);if(raw)scoped.initialRecord=JSON.parse(raw);}return invoke(ctx.env.OWNER_RAW_NAMESPACE||ctx.env.FINANCE_ACCOUNTS,ctx.username,'/owner-backup',scoped);}
